/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giacenze_crypto.com;



import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JTextArea;
import javax.swing.Timer;



/**
 *
 * @author luca.passelli
 */
public class Download extends javax.swing.JDialog {

    /**
     * Creates new form Attesa
     */
public int Massimo;
public int avanzamento;
public Thread thread;
public static boolean FineThread=false;

//    static boolean DownloadTerminato=false;
   // static boolean finito=false;

private Timer timer = new Timer(1000, new ActionListener() {

        private int counter = 1;

        @Override
        public void actionPerformed(ActionEvent ae) {
           // SetAvanzamento(counter);
           // bar.setValue(++counter);
           counter++;
            if (counter > 1000) {
                timer.stop();
            }
        }
    });





    public Download() {

     //   finestra=c;
      //  finestra.setEnabled(false);
  
         initComponents();
         Download.FineThread=false;
         
       /*  ByteArrayOutputStream baos = new ByteArrayOutputStream();
        System.setOut(new PrintStream(baos));*/
       
       
       //PARTE SOTTO OK PER GESTIONE ERRORI
    /*    PrintStream printStream = new PrintStream(new CustomOutputStream(textArea));
        System.setOut(printStream);
        System.setErr(printStream);*/
        
    
    
        // this.setVisible(true);

              
        // System.out.println(FileRemoto);
        // System.out.println(FileLocale);

     

    }
    
    public void SetThread(Thread T){
        thread=T;
    }
    
    public void NascondiBarra(){
        ProgressBarDownload.setVisible(false);
        LabelAvanzamento.setVisible(false);
    }
    
    public void NascondiInterrompi(){
        Bottone_Interrompi.setEnabled(false);
        Bottone_Interrompi.setVisible(false);
    }
    
    public Boolean FineThread(){
        
        if (thread!=null&&!thread.isAlive()){
            this.dispose();
        }
        return Download.FineThread;
    }
    
    public void NoModale(){
    this.setModalityType(ModalityType.MODELESS);
}
     public void Pausa(){
         timer.start();
     }
     
     public void SetLabel(String testo){
         this.LabelScaricamento.setText(testo);
     }
     
     public void Titolo(String testo){
         this.setTitle(testo);
     }
    
     public void SetMassimo(int Max){

                     Massimo=Max;
         ProgressBarDownload.setMaximum(Massimo);


     }
    
     public void SetAvanzamento (int Avanzamento) {
 //Thread thread = new Thread() {
 //           public void run() {
         avanzamento=Avanzamento;
         ProgressBarDownload.setValue(Avanzamento);
        // ProgressBarDownload.setStringPainted(true);
         LabelAvanzamento.setText("Elaborazione "+Avanzamento+" di "+Massimo);
 //}      };
// thread.start();

     }
     
          public void SetMessaggioAvanzamento (String Messaggio) {
 //Thread thread = new Thread() {
 //           public void run() {
        // avanzamento=Avanzamento;
        // ProgressBarDownload.setValue(Avanzamento);
         LabelAvanzamento.setText(Messaggio);
 //}      };
// thread.start();

     }
     
     public void ChiudiFinestra (){
        this.dispose();
     }
     
     
        public void updateProgress(int value) {
        ProgressBarDownload.setValue(value);
    }
 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelScaricamento = new javax.swing.JLabel();
        ProgressBarDownload = new javax.swing.JProgressBar();
        LabelAvanzamento = new javax.swing.JLabel();
        Bottone_Interrompi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        LabelScaricamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelScaricamento.setText("Importazione del file in corso....");

        ProgressBarDownload.setStringPainted(true);

        LabelAvanzamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAvanzamento.setText("Avanzamento");

        Bottone_Interrompi.setText("Interrompi");
        Bottone_Interrompi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_InterrompiActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProgressBarDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addComponent(LabelAvanzamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelScaricamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bottone_Interrompi, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelScaricamento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProgressBarDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelAvanzamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bottone_Interrompi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

      
    }//GEN-LAST:event_formWindowClosed

    private void Bottone_InterrompiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_InterrompiActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        Download.FineThread=true;
        Bottone_Interrompi.setBackground(Color.red);
        Bottone_Interrompi.setText("Interruzione in corso ...");

    }//GEN-LAST:event_Bottone_InterrompiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Interrompi;
    private javax.swing.JLabel LabelAvanzamento;
    private javax.swing.JLabel LabelScaricamento;
    private javax.swing.JProgressBar ProgressBarDownload;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables




   public class CustomOutputStream extends OutputStream {
  
       

    private JTextArea textArea;

    public CustomOutputStream(JTextArea textArea) {
        this.textArea = textArea;
    }

    @Override
    public void write(int b) throws IOException {
        // redirects data to the text area
        textArea.setText(textArea.getText() + String.valueOf((char)b));
     //   textArea.append(String.valueOf((char)b));
        // scrolls the text area to the end of data
    //    textArea.setCaretPosition(textArea.getDocument().getLength());
        // keeps the textArea up to date
    //    textArea.update(textArea.getGraphics());
    }
    
    
} 
    
    
    
    


}
