/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giacenze_crypto.com;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;



/**
 *
 * @author luca.passelli
 */
public class Download extends javax.swing.JDialog {

    /**
     * Creates new form Attesa
     */
public static int Massimo;
public static int avanzamento;
public static Component finestra;
//    static boolean DownloadTerminato=false;
   // static boolean finito=false;

private Timer timer = new Timer(1000, new ActionListener() {

        private int counter = 1;

        @Override
        public void actionPerformed(ActionEvent ae) {
           // SetAvanzamento(counter);
           // bar.setValue(++counter);
           counter++;
            if (counter > 1000) {
                timer.stop();
            }
        }
    });





    public Download() {
     //   finestra=c;
      //  finestra.setEnabled(false);
  
         initComponents();
        // this.setVisible(true);

              
        // System.out.println(FileRemoto);
        // System.out.println(FileLocale);

     

    }
    

     public void Pausa(){
         timer.start();
     }
     
     public void SetLabel(String testo){
         this.LabelScaricamento.setText(testo);
     }
     
     public void Titolo(String testo){
         this.setTitle(testo);
     }
    
     public void SetMassimo(int Max){

                     Massimo=Max;
         ProgressBarDownload.setMaximum(Massimo);


     }
    
     public void SetAvanzamento (int Avanzamento) {
 //Thread thread = new Thread() {
 //           public void run() {
         avanzamento=Avanzamento;
         ProgressBarDownload.setValue(Avanzamento);
         LabelAvanzamento.setText("Elaborazione "+Avanzamento+" di "+Massimo);
 //}      };
// thread.start();

     }
     
     public void ChiudiFinestra (){
         this.dispose();
     }
     
     
        public void updateProgress(int value) {
        ProgressBarDownload.setValue(value);
    }
 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelScaricamento = new javax.swing.JLabel();
        ProgressBarDownload = new javax.swing.JProgressBar();
        LabelAvanzamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        LabelScaricamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelScaricamento.setText("Importazione del file in corso....");

        LabelAvanzamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAvanzamento.setText("Avanzamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProgressBarDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(LabelAvanzamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelScaricamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelScaricamento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProgressBarDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelAvanzamento)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    //    finestra.setEnabled(true);
      //  finestra.requestFocus();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAvanzamento;
    private javax.swing.JLabel LabelScaricamento;
    private javax.swing.JProgressBar ProgressBarDownload;
    // End of variables declaration//GEN-END:variables
}
