/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giacenze_crypto.com;

import static giacenze_crypto.com.CDC_Grafica.Funzioni_isNumeric;
import java.awt.Color;
import java.util.Date;

/**
 *
 * @author luca.passelli
 */
public class MovimentoManuale_GUI extends javax.swing.JDialog {

    /**
     * Creates new form MovimentoManuale_GUI
     */
    public MovimentoManuale_GUI() {
        initComponents();
        EvidenziaProblemi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_Label = new javax.swing.JLabel();
        Data_Label = new javax.swing.JLabel();
        Data_Datachooser = new com.toedter.calendar.JDateChooser();
        Ora_Label = new javax.swing.JLabel();
        Ora_ComboBox = new javax.swing.JComboBox<>();
        Minuto_Label = new javax.swing.JLabel();
        Minuto_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscita_Label = new javax.swing.JLabel();
        MonetaEntrata_Label = new javax.swing.JLabel();
        MonetaUscita_TextField = new javax.swing.JTextField();
        MonetaEntrata_TextField = new javax.swing.JTextField();
        MonetaUscitaTipo_Label = new javax.swing.JLabel();
        MonetaEntrataTipo_Label = new javax.swing.JLabel();
        MonetaEntrataTipo_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscitaTipo_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscitaQuantita_Label = new javax.swing.JLabel();
        MonetaUscitaQuantita_TextField = new javax.swing.JTextField();
        MonetaEntrataQuantita_Label = new javax.swing.JLabel();
        MonetaEntrataQuantita_TextField = new javax.swing.JTextField();
        Freccia1_Label = new javax.swing.JLabel();
        Freccia2_Label = new javax.swing.JLabel();
        Freccia3_Label = new javax.swing.JLabel();
        Note_Label = new javax.swing.JLabel();
        Note_ScrollPane = new javax.swing.JScrollPane();
        Note_TextArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ValoreTransazione_Label = new javax.swing.JLabel();
        ValoreTransazione_TextField = new javax.swing.JTextField();
        Bottone_CalcolaAutomaticamente = new javax.swing.JButton();
        Bottone_Ok = new javax.swing.JButton();
        Bottone_Annulla = new javax.swing.JButton();
        ID_TextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Wallet_Label = new javax.swing.JLabel();
        WalletDettaglio_Label = new javax.swing.JLabel();
        Wallet_TextField = new javax.swing.JTextField();
        WalletDettaglio_TextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ID_Label.setText("ID Transazione : ");

        Data_Label.setText("Data : ");

        Data_Datachooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Data_DatachooserPropertyChange(evt);
            }
        });

        Ora_Label.setText("Ora : ");

        Ora_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        Ora_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ora_ComboBoxActionPerformed(evt);
            }
        });

        Minuto_Label.setText("Minuto : ");

        Minuto_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        MonetaUscita_Label.setText("Moneta Uscita : ");

        MonetaEntrata_Label.setText("Moneta Entrata : ");

        MonetaUscita_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MonetaUscita_TextFieldKeyReleased(evt);
            }
        });

        MonetaEntrata_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MonetaEntrata_TextFieldKeyReleased(evt);
            }
        });

        MonetaUscitaTipo_Label.setText("Tipo Moneta Uscita : ");

        MonetaEntrataTipo_Label.setText("Tipo Moneta Entrata : ");

        MonetaEntrataTipo_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Crypto", "NFT", "FIAT" }));
        MonetaEntrataTipo_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonetaEntrataTipo_ComboBoxItemStateChanged(evt);
            }
        });

        MonetaUscitaTipo_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Crypto", "NFT", "FIAT" }));
        MonetaUscitaTipo_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonetaUscitaTipo_ComboBoxItemStateChanged(evt);
            }
        });

        MonetaUscitaQuantita_Label.setText("Quantità Uscita : ");

        MonetaUscitaQuantita_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonetaUscitaQuantita_TextFieldActionPerformed(evt);
            }
        });
        MonetaUscitaQuantita_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MonetaUscitaQuantita_TextFieldKeyReleased(evt);
            }
        });

        MonetaEntrataQuantita_Label.setText("Quantità Entrata : ");

        MonetaEntrataQuantita_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MonetaEntrataQuantita_TextFieldKeyReleased(evt);
            }
        });

        Freccia1_Label.setText("->");

        Freccia2_Label.setText("->");

        Freccia3_Label.setText("->");

        Note_Label.setText("Note : ");

        Note_TextArea.setColumns(20);
        Note_TextArea.setRows(5);
        Note_ScrollPane.setViewportView(Note_TextArea);

        ValoreTransazione_Label.setText("Valore Transazione in EURO : ");

        ValoreTransazione_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ValoreTransazione_TextFieldKeyReleased(evt);
            }
        });

        Bottone_CalcolaAutomaticamente.setText("Calcola Automaticamente");

        Bottone_Ok.setText("OK");
        Bottone_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_OkActionPerformed(evt);
            }
        });

        Bottone_Annulla.setText("Annulla");

        ID_TextField.setEnabled(false);

        Wallet_Label.setText("Exchange / Wallet : ");

        WalletDettaglio_Label.setText("Dettagli Wallet : ");

        Wallet_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Wallet_TextFieldKeyReleased(evt);
            }
        });

        WalletDettaglio_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WalletDettaglio_TextFieldKeyReleased(evt);
            }
        });

        jComboBox1.setEditable(true);

        jComboBox2.setEditable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bottone_Ok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bottone_Annulla))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValoreTransazione_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValoreTransazione_TextField)
                                .addGap(18, 18, 18)
                                .addComponent(Bottone_CalcolaAutomaticamente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Note_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Note_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ID_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(MonetaUscitaTipo_Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MonetaUscitaTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(MonetaUscita_Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MonetaUscita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addComponent(MonetaUscitaQuantita_Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MonetaUscitaQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Freccia3_Label)
                                                    .addComponent(Freccia1_Label)
                                                    .addComponent(Freccia2_Label)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(Data_Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Data_Datachooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Ora_Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Ora_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(MonetaEntrata_Label)
                                                    .addComponent(MonetaEntrataTipo_Label)
                                                    .addComponent(MonetaEntrataQuantita_Label))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(MonetaEntrataTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(MonetaEntrata_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(MonetaEntrataQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(Minuto_Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Minuto_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Wallet_Label)
                            .addComponent(WalletDettaglio_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 269, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Wallet_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(WalletDettaglio_TextField))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_Label)
                    .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Data_Label)
                    .addComponent(Data_Datachooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ora_Label)
                        .addComponent(Ora_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Minuto_Label)
                        .addComponent(Minuto_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wallet_Label)
                    .addComponent(Wallet_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WalletDettaglio_Label)
                    .addComponent(WalletDettaglio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonetaUscita_Label)
                    .addComponent(MonetaEntrata_Label)
                    .addComponent(MonetaUscita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonetaEntrata_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Freccia1_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonetaUscitaTipo_Label)
                    .addComponent(MonetaEntrataTipo_Label)
                    .addComponent(MonetaEntrataTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonetaUscitaTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Freccia2_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonetaUscitaQuantita_Label)
                    .addComponent(MonetaUscitaQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonetaEntrataQuantita_Label)
                    .addComponent(MonetaEntrataQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Freccia3_Label))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValoreTransazione_Label)
                    .addComponent(ValoreTransazione_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_CalcolaAutomaticamente))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Note_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Note_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone_Ok)
                    .addComponent(Bottone_Annulla))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MonetaUscitaQuantita_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonetaUscitaQuantita_TextFieldActionPerformed
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscitaQuantita_TextFieldActionPerformed

    private void Ora_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ora_ComboBoxActionPerformed
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_Ora_ComboBoxActionPerformed

    private void Bottone_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_OkActionPerformed
        // TODO add your handling code here:
        EvidenziaProblemi();
        
    }//GEN-LAST:event_Bottone_OkActionPerformed

    private void Wallet_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Wallet_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
        
    }//GEN-LAST:event_Wallet_TextFieldKeyReleased

    private void WalletDettaglio_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WalletDettaglio_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_WalletDettaglio_TextFieldKeyReleased

    private void MonetaUscita_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonetaUscita_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscita_TextFieldKeyReleased

    private void MonetaUscitaQuantita_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonetaUscitaQuantita_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscitaQuantita_TextFieldKeyReleased

    private void MonetaEntrata_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonetaEntrata_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaEntrata_TextFieldKeyReleased

    private void MonetaEntrataQuantita_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonetaEntrataQuantita_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaEntrataQuantita_TextFieldKeyReleased

    private void ValoreTransazione_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValoreTransazione_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_ValoreTransazione_TextFieldKeyReleased

    private void MonetaUscitaTipo_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonetaUscitaTipo_ComboBoxItemStateChanged
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscitaTipo_ComboBoxItemStateChanged

    private void MonetaEntrataTipo_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonetaEntrataTipo_ComboBoxItemStateChanged
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaEntrataTipo_ComboBoxItemStateChanged

    private void Data_DatachooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Data_DatachooserPropertyChange
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_Data_DatachooserPropertyChange

    private boolean EvidenziaProblemi() {                                           
        // TODO add your handling code here:
        
        //per prima cosa sostituisco le virgole con i punti nei campi numerici
        MonetaUscitaQuantita_TextField.setText(MonetaUscitaQuantita_TextField.getText().replace(",", "."));
        MonetaEntrataQuantita_TextField.setText(MonetaEntrataQuantita_TextField.getText().replace(",", "."));
        ValoreTransazione_TextField.setText(ValoreTransazione_TextField.getText().replace(",", "."));
        
        //adesso leggo tutti gli oggetti e li metto in stringhe
        Date Data=this.Data_Datachooser.getDate();
        String MonetaU=this.MonetaUscita_TextField.getText().trim();
        String MonetaUQta=this.MonetaUscitaQuantita_TextField.getText().trim();
        String MonetaUTipo=this.MonetaUscitaTipo_ComboBox.getSelectedItem().toString();
        String MonetaE=this.MonetaEntrata_TextField.getText().trim();
        String MonetaEQta=this.MonetaEntrataQuantita_TextField.getText().trim();
        String MonetaETipo=this.MonetaEntrataTipo_ComboBox.getSelectedItem().toString();
        String ValoreTransazione=this.ValoreTransazione_TextField.getText().trim();
        String Wallet=this.Wallet_TextField.getText().trim();
        String WalletDettaglio=this.WalletDettaglio_TextField.getText().trim();
        
        //adesso testo tutti i campi e vedo se manca qualcosa, in quel caso evidenzio i campi mancanti
        boolean nonCompleto=false;
        if (Wallet.equalsIgnoreCase("")){
            nonCompleto=true;
            this.Wallet_TextField.setBackground(Color.getHSBColor(20, 20, 20));
        }else {
            this.Wallet_TextField.setBackground(Color.white);
        }
        
       if (WalletDettaglio.equalsIgnoreCase("")){
            nonCompleto=true;
            this.WalletDettaglio_TextField.setBackground(Color.getHSBColor(20, 20, 20));
        }else {
            this.WalletDettaglio_TextField.setBackground(Color.white);
        }
       
        if (ValoreTransazione.equalsIgnoreCase("")||!CDC_Grafica.Funzioni_isNumeric(ValoreTransazione)){
            nonCompleto=true;
            this.ValoreTransazione_TextField.setBackground(Color.getHSBColor(20, 20, 20));
        }else {
            this.ValoreTransazione_TextField.setBackground(Color.white);
        }
        
        if (Data==null){
            nonCompleto=true;
            this.Data_Datachooser.setBackground(Color.orange);
        }else {
            this.Data_Datachooser.setBackground(this.getBackground());
        }
        
        
        //in questa prima parte esamino se i blocchi sono interamente compilati o interamente vuoti
        boolean tuttoCompilatoE=false;
        boolean tuttoCompilatoU=false;
        boolean tuttoVuotoE=false;
        boolean tuttoVuotoU=false;
        if (MonetaU.equalsIgnoreCase("")&&MonetaUQta.equalsIgnoreCase("")&&MonetaUTipo.equalsIgnoreCase("-----"))
            {
            tuttoVuotoU=true;
            tuttoCompilatoU=false;
            }
        if (!MonetaU.equalsIgnoreCase("")&&!MonetaUQta.equalsIgnoreCase("")&&!MonetaUTipo.equalsIgnoreCase("-----"))
            {
            tuttoVuotoU=false;
            tuttoCompilatoU=true;
            }
        
        if (MonetaE.equalsIgnoreCase("")&&MonetaEQta.equalsIgnoreCase("")&&MonetaETipo.equalsIgnoreCase("-----"))
            {
            tuttoVuotoE=true;
            tuttoCompilatoE=false;
            }
        if (!MonetaE.equalsIgnoreCase("")&&!MonetaEQta.equalsIgnoreCase("")&&!MonetaETipo.equalsIgnoreCase("-----"))
            {
            tuttoVuotoE=false;
            tuttoCompilatoE=true;
            }
        //se trovo delle compilazioni a metà in uno dei 2 blocchi devo evidenziare il problema
        //se trovo che nessuno dei 2 blocchi è compilato devo evidenziare il problema
        //se invece le 2 situazioni di prima non sono vere vuol dire che va tutto bene

        
        //se trovo delle compilazioni a metà in uno dei 2 blocchi devo evidenziare il problema
        //oppure se trovo che nessuno dei 2 blocchi è compilato devo evidenziare il problema
        //oppure se i campi numerici non sono numerici devo evidenziare il problema
        if (((tuttoVuotoE==false&&tuttoCompilatoE==false)||(tuttoVuotoU==false&&tuttoCompilatoU==false))||
                (tuttoVuotoE==true&&tuttoVuotoU==true)||
                (!CDC_Grafica.Funzioni_isNumeric(MonetaUQta)||!CDC_Grafica.Funzioni_isNumeric(MonetaEQta))){
            nonCompleto=true;
            if (MonetaU.equalsIgnoreCase(""))MonetaUscita_TextField.setBackground(Color.getHSBColor(20, 20, 20));else MonetaUscita_TextField.setBackground(Color.white);
            if (MonetaUQta.equalsIgnoreCase("")||!CDC_Grafica.Funzioni_isNumeric(MonetaUQta))MonetaUscitaQuantita_TextField.setBackground(Color.getHSBColor(20, 20, 20));else MonetaUscitaQuantita_TextField.setBackground(Color.white);
            if (MonetaUTipo.equalsIgnoreCase("-----"))MonetaUscitaTipo_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));else MonetaUscitaTipo_ComboBox.setBackground(Color.white);
            if (MonetaE.equalsIgnoreCase(""))MonetaEntrata_TextField.setBackground(Color.getHSBColor(20, 20, 20));else MonetaEntrata_TextField.setBackground(Color.white);
            if (MonetaEQta.equalsIgnoreCase("")||!CDC_Grafica.Funzioni_isNumeric(MonetaEQta))MonetaEntrataQuantita_TextField.setBackground(Color.getHSBColor(20, 20, 20));else MonetaEntrataQuantita_TextField.setBackground(Color.white);
            if (MonetaETipo.equalsIgnoreCase("-----"))MonetaEntrataTipo_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));else MonetaEntrataTipo_ComboBox.setBackground(Color.white);
        } 
        //se invece le 2 situazioni di prima non sono vere vuol dire che va tutto bene
        else{
            MonetaUscita_TextField.setBackground(Color.white);
            MonetaUscitaQuantita_TextField.setBackground(Color.white);
            MonetaUscitaTipo_ComboBox.setBackground(Color.white);
            MonetaEntrata_TextField.setBackground(Color.white);
            MonetaEntrataQuantita_TextField.setBackground(Color.white);
            MonetaEntrataTipo_ComboBox.setBackground(Color.white);
            
            }
        
               if (!nonCompleto)Bottone_Ok.setEnabled(true);
        else Bottone_Ok.setEnabled(false);
    return nonCompleto;
    
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentoManuale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentoManuale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentoManuale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentoManuale_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentoManuale_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Annulla;
    private javax.swing.JButton Bottone_CalcolaAutomaticamente;
    private javax.swing.JButton Bottone_Ok;
    private com.toedter.calendar.JDateChooser Data_Datachooser;
    private javax.swing.JLabel Data_Label;
    private javax.swing.JLabel Freccia1_Label;
    private javax.swing.JLabel Freccia2_Label;
    private javax.swing.JLabel Freccia3_Label;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JComboBox<String> Minuto_ComboBox;
    private javax.swing.JLabel Minuto_Label;
    private javax.swing.JLabel MonetaEntrataQuantita_Label;
    private javax.swing.JTextField MonetaEntrataQuantita_TextField;
    private javax.swing.JComboBox<String> MonetaEntrataTipo_ComboBox;
    private javax.swing.JLabel MonetaEntrataTipo_Label;
    private javax.swing.JLabel MonetaEntrata_Label;
    private javax.swing.JTextField MonetaEntrata_TextField;
    private javax.swing.JLabel MonetaUscitaQuantita_Label;
    private javax.swing.JTextField MonetaUscitaQuantita_TextField;
    private javax.swing.JComboBox<String> MonetaUscitaTipo_ComboBox;
    private javax.swing.JLabel MonetaUscitaTipo_Label;
    private javax.swing.JLabel MonetaUscita_Label;
    private javax.swing.JTextField MonetaUscita_TextField;
    private javax.swing.JLabel Note_Label;
    private javax.swing.JScrollPane Note_ScrollPane;
    private javax.swing.JTextArea Note_TextArea;
    private javax.swing.JComboBox<String> Ora_ComboBox;
    private javax.swing.JLabel Ora_Label;
    private javax.swing.JLabel ValoreTransazione_Label;
    private javax.swing.JTextField ValoreTransazione_TextField;
    private javax.swing.JLabel WalletDettaglio_Label;
    private javax.swing.JTextField WalletDettaglio_TextField;
    private javax.swing.JLabel Wallet_Label;
    private javax.swing.JTextField Wallet_TextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
