/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.giacenzecrypto.giacenze_crypto;

import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 * Riferimento estero di un gruppo wallet per il quadro W/RW : o uno Stato estero +
 * identificativo fiscale inseriti a mano, o un exchange dell'anagrafica da cui ricavarli.
 *
 * <p>Scrive su {@code GRUPPO_RIFERIMENTO_ESTERO} tramite
 * {@link Principale_GruppiWalletRW#salvaRiferimento}. {@link #salvato} dice al chiamante
 * se aggiornare la tabella dei gruppi.</p>
 */
public class GUI_RiferimentoEsteroGruppo extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private final String gruppo;

    /** {@code true} se l'utente ha salvato (il chiamante deve rinfrescare la tabella gruppi). */
    public boolean salvato = false;

    public GUI_RiferimentoEsteroGruppo(String gruppo) {
        this.gruppo = gruppo;
        ImageIcon icon = new ImageIcon(VarStatiche.getPathRisorse() + "logo.png");
        this.setIconImage(icon.getImage());
        initComponents();

        ButtonGroup bg = new ButtonGroup();
        bg.add(Radio_Stato);
        bg.add(Radio_Exchange);

        setTitle("Riferimento estero — " + gruppo);
        Label_Titolo.setText("Riferimento estero del gruppo \"" + gruppo + "\"");

        popolaCombo();
        caricaValoriCorrenti();
        setLocationRelativeTo(null);
    }

    private void popolaCombo() {
        Object selezionato = ComboBox_Exchange.getSelectedItem();
        ComboBox_Exchange.removeAllItems();
        for (String[] r : DatabaseH2.Pers_ExchangeAnagrafica_LeggiTabella().values()) {
            String nome = r[1] != null && !r[1].isBlank() ? r[1] : r[0];
            String stato = r[2] != null && !r[2].isBlank() ? r[2] : "—";
            ComboBox_Exchange.addItem(r[0] + "   ·   " + nome + "  (stato " + stato + ")");
        }
        if (selezionato != null) {
            ComboBox_Exchange.setSelectedItem(selezionato);
        }
    }

    /** Dall'item della combo (" id   ·   Nome ...") ricava l'id dell'exchange. */
    private static String idDaItem(Object item) {
        if (item == null) {
            return "";
        }
        String s = item.toString();
        int i = s.indexOf("   ·   ");
        return (i >= 0 ? s.substring(0, i) : s).trim();
    }

    private void selezionaExchange(String id) {
        if (id == null || id.isBlank()) {
            return;
        }
        for (int i = 0; i < ComboBox_Exchange.getItemCount(); i++) {
            if (id.equalsIgnoreCase(idDaItem(ComboBox_Exchange.getItemAt(i)))) {
                ComboBox_Exchange.setSelectedIndex(i);
                return;
            }
        }
    }

    private void caricaValoriCorrenti() {
        String[] r = DatabaseH2.Pers_GruppoRiferimento_Leggi(gruppo);
        boolean exchange = Principale_GruppiWalletRW.RIFERIMENTO_EXCHANGE.equals(r[1]);
        Radio_Exchange.setSelected(exchange);
        Radio_Stato.setSelected(!exchange);
        TextField_Stato.setText(r[2] == null ? "" : r[2]);
        TextField_PIva.setText(r[3] == null ? "" : r[3]);
        selezionaExchange(r[4]);
        aggiornaAbilitazione();
    }

    private void aggiornaAbilitazione() {
        boolean stato = Radio_Stato.isSelected();
        Label_Stato.setEnabled(stato);
        TextField_Stato.setEnabled(stato);
        Label_PIva.setEnabled(stato);
        TextField_PIva.setEnabled(stato);
        Label_Exchange.setEnabled(!stato);
        ComboBox_Exchange.setEnabled(!stato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Titolo = new javax.swing.JLabel();
        Radio_Stato = new javax.swing.JRadioButton();
        Radio_Exchange = new javax.swing.JRadioButton();
        Label_Stato = new javax.swing.JLabel();
        TextField_Stato = new javax.swing.JTextField();
        Label_PIva = new javax.swing.JLabel();
        TextField_PIva = new javax.swing.JTextField();
        Label_Exchange = new javax.swing.JLabel();
        ComboBox_Exchange = new javax.swing.JComboBox();
        Bottone_GestisciAnagrafica = new javax.swing.JButton();
        Bottone_Salva = new javax.swing.JButton();
        Bottone_Annulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Riferimento estero del gruppo");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        Label_Titolo.setText("Riferimento estero del gruppo");

        Radio_Stato.setText("Stato estero e identificativo fiscale inseriti a mano");
        Radio_Stato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_StatoActionPerformed(evt);
            }
        });

        Radio_Exchange.setText("Ricava da un exchange dell'anagrafica");
        Radio_Exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_ExchangeActionPerformed(evt);
            }
        });

        Label_Stato.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Label_Stato.setText("Codice Stato estero (max 3) :");

        Label_PIva.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Label_PIva.setText("Identificativo fiscale / P.IVA :");

        Label_Exchange.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Label_Exchange.setText("Exchange :");

        Bottone_GestisciAnagrafica.setText("Anagrafica exchange...");
        Bottone_GestisciAnagrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_GestisciAnagraficaActionPerformed(evt);
            }
        });

        Bottone_Salva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Salva.setText("Salva");
        Bottone_Salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_SalvaActionPerformed(evt);
            }
        });

        Bottone_Annulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Annulla.png"))); // NOI18N
        Bottone_Annulla.setText("Annulla");
        Bottone_Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AnnullaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Titolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Radio_Stato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Radio_Exchange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Bottone_Salva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Annulla))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_Stato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Stato, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_PIva, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_PIva, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_Exchange, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox_Exchange, 0, 280, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bottone_GestisciAnagrafica)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Radio_Stato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Stato)
                    .addComponent(TextField_Stato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_PIva)
                    .addComponent(TextField_PIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Radio_Exchange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Exchange)
                    .addComponent(ComboBox_Exchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_GestisciAnagrafica))
                .addGap(24, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bottone_Salva)
                    .addComponent(Bottone_Annulla))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Radio_StatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_StatoActionPerformed
        aggiornaAbilitazione();
    }//GEN-LAST:event_Radio_StatoActionPerformed

    private void Radio_ExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_ExchangeActionPerformed
        aggiornaAbilitazione();
    }//GEN-LAST:event_Radio_ExchangeActionPerformed

    private void Bottone_GestisciAnagraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_GestisciAnagraficaActionPerformed
        new GUI_AnagraficaExchange().setVisible(true);
        popolaCombo();
    }//GEN-LAST:event_Bottone_GestisciAnagraficaActionPerformed

    private void Bottone_SalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_SalvaActionPerformed
        String modalita = Radio_Exchange.isSelected()
                ? Principale_GruppiWalletRW.RIFERIMENTO_EXCHANGE
                : Principale_GruppiWalletRW.RIFERIMENTO_STATO;
        String exchangeId = idDaItem(ComboBox_Exchange.getSelectedItem());

        List<String> errori = Principale_GruppiWalletRW.salvaRiferimento(
                gruppo, modalita, TextField_Stato.getText(), TextField_PIva.getText(), exchangeId);
        if (!errori.isEmpty()) {
            Messaggi.WarningMessage("Dati non validi", String.join("\n", errori), this);
            return;
        }
        salvato = true;
        dispose();
    }//GEN-LAST:event_Bottone_SalvaActionPerformed

    private void Bottone_AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AnnullaActionPerformed
        dispose();
    }//GEN-LAST:event_Bottone_AnnullaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Annulla;
    private javax.swing.JButton Bottone_GestisciAnagrafica;
    private javax.swing.JButton Bottone_Salva;
    private javax.swing.JComboBox ComboBox_Exchange;
    private javax.swing.JLabel Label_Exchange;
    private javax.swing.JLabel Label_PIva;
    private javax.swing.JLabel Label_Stato;
    private javax.swing.JLabel Label_Titolo;
    private javax.swing.JRadioButton Radio_Exchange;
    private javax.swing.JRadioButton Radio_Stato;
    private javax.swing.JTextField TextField_PIva;
    private javax.swing.JTextField TextField_Stato;
    // End of variables declaration//GEN-END:variables
}
