/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.giacenzecrypto.giacenze_crypto;

import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Anagrafica degli exchange : per ognuno, stato estero (quadro W/RW) e identificativo
 * fiscale / P.IVA o equivalente (ISEE futura), piu' note / fonte / data aggiornamento.
 *
 * <p>CRUD diretto sulla tabella {@code EXCHANGE_ANAGRAFICA} di {@code personale.mv.db}
 * (API {@code DatabaseH2.Pers_ExchangeAnagrafica_*}, Fase 1). Nessun dato fiscale viene
 * pre-compilato : lo inserisce l'utente da fonte ufficiale.</p>
 */
public class GUI_AnagraficaExchange extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    public GUI_AnagraficaExchange() {
        ImageIcon icon = new ImageIcon(VarStatiche.getPathRisorse() + "logo.png");
        this.setIconImage(icon.getImage());
        initComponents();
        Tabelle.Tabelle_ApplicaHeaderBoldCentrato(Tabella);
        caricaTabella();
        setLocationRelativeTo(null);
    }

    /** Ricarica la tabella dal database. */
    private void caricaTabella() {
        DefaultTableModel m = (DefaultTableModel) Tabella.getModel();
        m.setRowCount(0);
        for (String[] r : DatabaseH2.Pers_ExchangeAnagrafica_LeggiTabella().values()) {
            m.addRow(new Object[]{r[0], vuotoSeNull(r[1]), vuotoSeNull(r[2]), vuotoSeNull(r[3]),
                vuotoSeNull(r[4]), vuotoSeNull(r[5]), vuotoSeNull(r[6])});
        }
    }

    private static String vuotoSeNull(String s) {
        return s == null ? "" : s;
    }

    private static String cella(Object o) {
        return o == null ? "" : o.toString().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabella = new javax.swing.JTable();
        Label_Info = new javax.swing.JLabel();
        Bottone_Aggiungi = new javax.swing.JButton();
        Bottone_Rimuovi = new javax.swing.JButton();
        Bottone_Salva = new javax.swing.JButton();
        Bottone_Chiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anagrafica Exchange");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        Tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exchange (id)", "Nome", "Stato estero", "Identificativo fiscale", "Note", "Fonte", "Aggiornato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabella);

        Label_Info.setText("Stato estero e identificativo fiscale degli exchange. Lo stato serve al quadro W/RW, l'identificativo fiscale servira' all'ISEE. Compila solo cio' che ti risulta da fonte ufficiale.");

        Bottone_Aggiungi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Nuovo.png"))); // NOI18N
        Bottone_Aggiungi.setText("Aggiungi");
        Bottone_Aggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AggiungiActionPerformed(evt);
            }
        });

        Bottone_Rimuovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Cestino.png"))); // NOI18N
        Bottone_Rimuovi.setText("Rimuovi selezionato");
        Bottone_Rimuovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_RimuoviActionPerformed(evt);
            }
        });

        Bottone_Salva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Salva.setText("Salva");
        Bottone_Salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_SalvaActionPerformed(evt);
            }
        });

        Bottone_Chiudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Annulla.png"))); // NOI18N
        Bottone_Chiudi.setText("Chiudi");
        Bottone_Chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_ChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bottone_Aggiungi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Rimuovi)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Bottone_Salva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Chiudi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bottone_Aggiungi)
                    .addComponent(Bottone_Rimuovi)
                    .addComponent(Bottone_Salva)
                    .addComponent(Bottone_Chiudi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone_AggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AggiungiActionPerformed
        String id = JOptionPane.showInputDialog(this,
                "Identificativo breve dell'exchange (es. \"binance\") :", "Nuovo exchange",
                JOptionPane.PLAIN_MESSAGE);
        if (id == null) {
            return;
        }
        id = id.trim().toLowerCase();
        if (id.isEmpty()) {
            Messaggi.WarningMessage("Campo non valido", "L'identificativo non puo' essere vuoto.", this);
            return;
        }
        DefaultTableModel m = (DefaultTableModel) Tabella.getModel();
        for (int i = 0; i < m.getRowCount(); i++) {
            if (id.equalsIgnoreCase(cella(m.getValueAt(i, 0)))) {
                Messaggi.WarningMessage("Gia' presente", "L'exchange \"" + id + "\" e' gia' in elenco.", this);
                return;
            }
        }
        m.addRow(new Object[]{id, "", "", "", "", "", ""});
        int r = m.getRowCount() - 1;
        Tabella.setRowSelectionInterval(r, r);
        Tabella.scrollRectToVisible(Tabella.getCellRect(r, 0, true));
    }//GEN-LAST:event_Bottone_AggiungiActionPerformed

    private void Bottone_RimuoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_RimuoviActionPerformed
        int riga = Tabella.getSelectedRow();
        if (riga < 0) {
            return;
        }
        int rigaModello = Tabella.convertRowIndexToModel(riga);
        ((DefaultTableModel) Tabella.getModel()).removeRow(rigaModello);
    }//GEN-LAST:event_Bottone_RimuoviActionPerformed

    private void Bottone_SalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_SalvaActionPerformed
        DefaultTableModel m = (DefaultTableModel) Tabella.getModel();

        Set<String> idInTabella = new LinkedHashSet<>();
        for (int i = 0; i < m.getRowCount(); i++) {
            String id = cella(m.getValueAt(i, 0)).toLowerCase();
            if (id.isEmpty()) {
                continue;
            }
            idInTabella.add(id);
            DatabaseH2.Pers_ExchangeAnagrafica_Scrivi(id,
                    nz(cella(m.getValueAt(i, 1))), nz(cella(m.getValueAt(i, 2))),
                    nz(cella(m.getValueAt(i, 3))), nz(cella(m.getValueAt(i, 4))),
                    nz(cella(m.getValueAt(i, 5))), nz(cella(m.getValueAt(i, 6))));
        }
        // righe tolte dalla tabella : le cancello anche dal database
        for (String id : DatabaseH2.Pers_ExchangeAnagrafica_LeggiTabella().keySet()) {
            if (!idInTabella.contains(id.toLowerCase())) {
                DatabaseH2.Pers_ExchangeAnagrafica_Cancella(id);
            }
        }
        caricaTabella();
        Messaggi.InfoMessage("Salvato", "Anagrafica exchange salvata.", this);
    }//GEN-LAST:event_Bottone_SalvaActionPerformed

    private void Bottone_ChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_ChiudiActionPerformed
        dispose();
    }//GEN-LAST:event_Bottone_ChiudiActionPerformed

    private static String nz(String s) {
        return s == null || s.isEmpty() ? null : s;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Aggiungi;
    private javax.swing.JButton Bottone_Chiudi;
    private javax.swing.JButton Bottone_Rimuovi;
    private javax.swing.JButton Bottone_Salva;
    private javax.swing.JLabel Label_Info;
    private javax.swing.JTable Tabella;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
