/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.giacenzecrypto.giacenze_crypto;

import static com.giacenzecrypto.giacenze_crypto.CDC_Grafica.MappaCryptoWallet;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author luca.passelli
 */

/*
Funzioni da sistemare per aggiungere nuova rete

-> Prezzi.RecuperaCoinsCoingecko
-> Funzioni.CompilaMappaChain
-> GestioneWallets

*/
public class GUI_ExchangeAPI extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    Map<String, String> Mappa_Exchange = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    /**
     * Creates new form GestioneWallets
     */

    
    public boolean TabellaDaAggiornare=false;
    public GUI_ExchangeAPI() {
        ImageIcon icon = new ImageIcon(Statiche.getPathRisorse()+"logo.png");
        this.setIconImage(icon.getImage());
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Pannello_Chiavi = new javax.swing.JPanel();
        ScrollPaneTabellaWallets = new javax.swing.JScrollPane();
        TabellaWallets = new javax.swing.JTable();
        TextField_ApiKey = new javax.swing.JTextField();
        Label_IndirizzoWallet1 = new javax.swing.JLabel();
        Label_IndirizzoWallet = new javax.swing.JLabel();
        TextField_ApiSecret = new javax.swing.JTextField();
        Label_Exchange = new javax.swing.JLabel();
        ComboBox_Exchange = new javax.swing.JComboBox<>();
        Bottone_InserisciChiave = new javax.swing.JButton();
        Bottone_RimuoviChiave = new javax.swing.JButton();
        Bottone_AggiornaSelezionati = new javax.swing.JButton();
        Bottone_Aggiorna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabellaWallets.setAutoCreateRowSorter(true);
        TabellaWallets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Gruppo", "Exchange", "API Key", "API Secret", "<html><center>Data Ultimo Movimento<br>Importato</html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPaneTabellaWallets.setViewportView(TabellaWallets);
        if (TabellaWallets.getColumnModel().getColumnCount() > 0) {
            TabellaWallets.getColumnModel().getColumn(0).setPreferredWidth(150);
            TabellaWallets.getColumnModel().getColumn(0).setMaxWidth(150);
            TabellaWallets.getColumnModel().getColumn(1).setPreferredWidth(150);
            TabellaWallets.getColumnModel().getColumn(1).setMaxWidth(150);
            TabellaWallets.getColumnModel().getColumn(4).setPreferredWidth(150);
            TabellaWallets.getColumnModel().getColumn(4).setMaxWidth(150);
        }
        TabellaWallets.getTableHeader().setPreferredSize(new Dimension(TabellaWallets.getColumnModel().getTotalColumnWidth(), 48));

        Label_IndirizzoWallet1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_IndirizzoWallet1.setText("Api Key :");

        Label_IndirizzoWallet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_IndirizzoWallet.setText("Api Secret :");

        Label_Exchange.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_Exchange.setText("Exchange :");

        ComboBox_Exchange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- nessuna selezione ---", "Binance" }));

        Bottone_InserisciChiave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Nuovo.png"))); // NOI18N
        Bottone_InserisciChiave.setText("Inserisci Chiave");
        Bottone_InserisciChiave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_InserisciChiaveActionPerformed(evt);
            }
        });

        Bottone_RimuoviChiave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Cestino.png"))); // NOI18N
        Bottone_RimuoviChiave.setText("Rimuovi Wallet Selezionato");
        Bottone_RimuoviChiave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_RimuoviChiaveActionPerformed(evt);
            }
        });

        Bottone_AggiornaSelezionati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Aggiorna.png"))); // NOI18N
        Bottone_AggiornaSelezionati.setText("Aggiorna Selezionati");
        Bottone_AggiornaSelezionati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AggiornaSelezionatiActionPerformed(evt);
            }
        });

        Bottone_Aggiorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Aggiorna.png"))); // NOI18N
        Bottone_Aggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AggiornaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pannello_ChiaviLayout = new javax.swing.GroupLayout(Pannello_Chiavi);
        Pannello_Chiavi.setLayout(Pannello_ChiaviLayout);
        Pannello_ChiaviLayout.setHorizontalGroup(
            Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pannello_ChiaviLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Label_IndirizzoWallet1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_IndirizzoWallet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(Label_Exchange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Pannello_ChiaviLayout.createSequentialGroup()
                        .addComponent(ComboBox_Exchange, 0, 222, Short.MAX_VALUE)
                        .addGap(92, 92, 92)
                        .addComponent(Bottone_InserisciChiave))
                    .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextField_ApiSecret, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                        .addComponent(TextField_ApiKey, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone_RimuoviChiave, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(Bottone_AggiornaSelezionati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(Bottone_Aggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pannello_ChiaviLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ScrollPaneTabellaWallets)
                    .addContainerGap()))
        );
        Pannello_ChiaviLayout.setVerticalGroup(
            Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pannello_ChiaviLayout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pannello_ChiaviLayout.createSequentialGroup()
                        .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_ApiKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_IndirizzoWallet1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_IndirizzoWallet)
                            .addComponent(TextField_ApiSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Exchange)
                            .addComponent(ComboBox_Exchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bottone_InserisciChiave))
                        .addGap(7, 7, 7))
                    .addGroup(Pannello_ChiaviLayout.createSequentialGroup()
                        .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bottone_Aggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Pannello_ChiaviLayout.createSequentialGroup()
                                .addComponent(Bottone_RimuoviChiave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bottone_AggiornaSelezionati)))
                        .addGap(29, 29, 29))))
            .addGroup(Pannello_ChiaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pannello_ChiaviLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ScrollPaneTabellaWallets, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        Bottone_Aggiorna.setText("<html>Scarica nuovi movimenti<br>da tutti i Wallet della lista</html>");

        jTabbedPane1.addTab("Chiavi API", Pannello_Chiavi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /*  public static boolean isValidAddress(String address,String Rete) {
        if (Rete.equalsIgnoreCase("SOL")){
           // String BASE58_REGEX = "^[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]+$";
           // return address != null && address.length() == 44 && Pattern.matches(BASE58_REGEX, address);
            return isValidSolanaAddress(address);
        }
        else{
            Pattern ETH_ADDRESS_PATTERN = Pattern.compile("^0x[a-fA-F0-9]{40}$");
            return address != null && ETH_ADDRESS_PATTERN.matcher(address).matches();
        }
    }
    
    private static boolean isValidSolanaAddress(String address) {
        try {
            byte[] decoded = Base58.decode(address);
            return decoded.length == 32; // Gli indirizzi Solana devono essere di 32 byte decodificati
        } catch (Exception e) {
            return false;
        }
    }
    */
    
    private void Bottone_InserisciChiaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_InserisciChiaveActionPerformed
        // TODO add your handling code here:
        Map<String, String> MappaWallets=DatabaseH2.Pers_Wallets_LeggiTabella();
        String Wallet=TextField_ApiSecret.getText().trim();
        String Rete=ComboBox_Exchange.getItemAt(ComboBox_Exchange.getSelectedIndex());
        if (Rete.split("\\(").length>1){
            Rete=Rete.split("\\(")[1].trim().substring(0, Rete.split("\\(")[1].length()-1);
        } else {
        }
        if(ComboBox_Exchange.getSelectedIndex()==0){
            //non è valido la selezione della combobox
            JOptionPane.showConfirmDialog(this, "Attenzione! \nDevi selezionare una rete valida",
                            "Rete non valida",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,null);            
        }
        else if (!Funzioni_WalletDeFi.isValidAddress(Wallet,Rete)){
                //non è un indirizzo di wallet valido
            JOptionPane.showConfirmDialog(this, "Attenzione! \nIl Wallet specificato non è valido",
                            "Wallet non Valido",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
        }
        else{
            //Se arrivo qui i dati sono corretti adesso devo
            //1 - Controllare se non esiste già un wallet della stessa rete con lo stesso indirizzo
            if (MappaWallets.get(Wallet+"_"+Rete)!=null){
                JOptionPane.showConfirmDialog(this, "Attenzione! \nWallet gia' prensente nella lista",
                            "Wallet gia' presente",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,null);  
            }
            //2 - Inserisco il wallet nella lista
            else{
               // MappaWallets.put(Wallet+"_"+Rete, Wallet+";"+Rete);
                DatabaseH2.Pers_Wallets_Scrivi(Wallet, Rete);
                System.out.println("Scrivo il Wallet nel Database : "+Wallet+"_"+Rete);
               // ScriviFileWallets();
                PopolaTabella();
            }
        }
    }//GEN-LAST:event_Bottone_InserisciChiaveActionPerformed

    
    private void PopolaTabella(){
        
        

        DefaultTableModel ModelloTabellaWallets = (DefaultTableModel) TabellaWallets.getModel();
        Tabelle.Funzioni_PulisciTabella(ModelloTabellaWallets);
       // Map<String, String> MappaWallets=DatabaseH2.Pers_Wallets_LeggiTabella();
        //prima di fare il tutto dovrei scorrere tutti i miei wallet e vedere se trovo corrispondenze con quelli in tabella
        //se così è allora devo cercare la data dell'ultimo movimento e segnarlo nella tabella
        Mappa_Exchange.clear();
        for (String[] v : MappaCryptoWallet.values()) {
                    Mappa_Exchange.put(v[3], Funzioni.getOradaID(v[0]));  
        }
        //Questa sotto è la mappa dei wallet nella tabella
        for (String splittata[]:DatabaseH2.Pers_ExchangeApi_LeggiTabella().values())
        {
                String rigaTabella[]=new String[5];
                String w=splittata[0];
                rigaTabella[0]=DatabaseH2.Pers_GruppoWallet_Leggi(w);
                rigaTabella[0]=DatabaseH2.Pers_GruppoAlias_Leggi(rigaTabella[0])[1];
                rigaTabella[1]=splittata[1];
                rigaTabella[2]=splittata[2];
                rigaTabella[3]=splittata[3];
                if (Mappa_Exchange.get(w)==null){
                    rigaTabella[4]="0";
                }
                else{
                    rigaTabella[4]=Mappa_Exchange.get(w);
                }
                    
                ModelloTabellaWallets.addRow(rigaTabella);            
            }

    }
    
    
    
    public void AggiornaWallets(List<String> selezionati) {
        Component c = com.giacenzecrypto.giacenze_crypto.GUI_ExchangeAPI.this;
        Download progress = new Download();
        progress.setLocationRelativeTo(this);
        Map<String, String> MappaWallets=DatabaseH2.Pers_Wallets_LeggiTabella();
//progress.RipristinaStdout();


        Thread thread;
        thread = new Thread() {
            public void run() {
                int i = 0;
                List<String> Portafogli = new ArrayList<>();
                if (selezionati==null){
                for (String riga : MappaWallets.values()) {
                    String splittata[] = riga.split(";");
                    String blocco = Mappa_Exchange.get(splittata[0] + " (" + splittata[1] + ")");
                    if (blocco != null) {
                        blocco = blocco.split(";")[1];
                    } else {
                        blocco = "0";
                    }
                    //boolean retecompatibile=false;
                    for(String rete : CDC_Grafica.Mappa_ChainExplorer.keySet()){
                        if (rete.equalsIgnoreCase(splittata[1]))
                        {
                           if (selezionati==null)  {
                                Portafogli.add(splittata[0] + ";" + blocco+";"+splittata[1]);
                           }else{
                               for(String p:selezionati){
                                   if (p.equals(splittata[0])){
                                       Portafogli.add(splittata[0] + ";" + blocco+";"+splittata[1]);
                                   }
                               }
                           }
                        }
                    }
                 /*   if (splittata[1].equalsIgnoreCase("BSC")
                            ||splittata[1].equalsIgnoreCase("CRO")
                            ||splittata[1].equalsIgnoreCase("ETH")
                            ||splittata[1].equalsIgnoreCase("BASE")
                            ||splittata[1].equalsIgnoreCase("ARB")
                            ||splittata[1].equalsIgnoreCase("SOL")
                            ||splittata[1].equalsIgnoreCase("BERA")
                            ) {
                        Portafogli.add(splittata[0] + ";" + blocco+";"+splittata[1]);
                    }*/
                }
                }else{
                    Portafogli=selezionati;
                    }

                //Tutte le nuove operazioni trovat vengono messe nella mappaTransazioniDefi
                Map<String,String[]> Mappa_Wallet_Dati = new TreeMap<>();
                Map<String, TransazioneDefi> MappaTransazioniDefi = Importazioni.DeFi_RitornaTransazioni(Portafogli, c, progress);
               // System.out.println("DIM:"+MappaTransazioniDefi.size());
                if (MappaTransazioniDefi != null) {
                    //Scrivo tutte le nuove transazioni nella mappa principale
                    for (TransazioneDefi v : MappaTransazioniDefi.values()) {
                        for (String[] st : v.RitornaRigheTabella()) {
                            CDC_Grafica.Funzione_AggiornaMappaWallets(st);//questo aggiorna la tabella wallet
                            //deve essere aggiornata perchè serve per sistemare poi le giacenze dei cronos
                            Importazioni.InserisciMovimentosuMappaCryptoWallet(st[0], st);
                         //   MappaCryptoWallet.put(st[0], st);
                            i++;
                            
                            //Questa parte serve per memorizzare in una mappa tutti i wallet che hanno avuto aggiornamenti con questa funzione
                            //in questo modo posso poi andare a cercare le giacenze di fine importazione per quanbto riguarda il token di riferimento
                            //ad es. eth per base, o bnb per la binance smart chain
                            //Salto la cronoschain perchè quella viene gestita a parte
                            String WalletRete=st[3];
                            String Wallet=st[3].split("\\(")[0].trim();
                            String ReteW=Funzioni.TrovaReteDaID(st[0]);
                            String Dati[]=new String[]{Wallet,ReteW};
                            if (!ReteW.equals("CRO"))Mappa_Wallet_Dati.put(WalletRete,Dati);

                            
                        }
                    }
                    
                    //Adesso per ogni wallet coinvolto controllo le giacenze di fine importazione e sistemo in caso di discrepanze
                    //Salto la cronoschain perchè quella viene gestita a parte
                    int r= JOptionPane.showConfirmDialog(c, "Vuoi che venga controllata la giacenza del token di riferimento delle chain \n"
                         + "e in caso di differenze creato un movimento di rettifica ?",
                            "Rettifiche movimenti",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                 
              //  System.out.println(r);
                if(r==0){
                    //System.out.println("Sistemo le giacenze");
                    for (String Dati[]:Mappa_Wallet_Dati.values()){
                         //System.out.println(Dati[0]);
                        Importazioni.DeFi_GiacenzeL1_Sistema(Dati[0], Dati[1], c, progress);
                    }}
                   // Importazioni.DeFi_GiacenzeL1_Rimanze(Portafogli,"pippo");
                 //   Prezzi.ScriviFileConversioneXXXEUR();
                    Importazioni.TransazioniAggiunte = i;
                    if (Importazioni.TransazioniAggiunte != 0) {
                        CDC_Grafica.TabellaCryptodaAggiornare = true;
                    }
                    
                }
                
                progress.dispose();

            }
        };
        progress.SetThread(thread);
        thread.start();
        progress.setVisible(true);
        //progress parte in modalità esclusiva quindi le istruzioni qua sotto non vengono eseguite fino a che la finestra non viene chiusa
        Importazioni.ConvertiScambiLPinDepositiPrelievi();
        CorreggiGiacenzeCronos();
        JOptionPane.showConfirmDialog(c, "Importazione Terminata \nSono stati inseriti " + Importazioni.TransazioniAggiunte + " nuovi movimenti",
                "Importazione Terminata", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
        PopolaTabella();
        c.setCursor(Cursor.getDefaultCursor());

    }
 
    private void CorreggiGiacenzeCronos() {
         Component c = this;
        Download progress = new Download();
        progress.setLocationRelativeTo(this);
                Thread thread;
        thread = new Thread() {
            public void run() {
                //Importazioni.GiacenzeCRO_Sistema("", c, progress, thread);
                        for (String v : Mappa_Exchange.keySet()) {
                            if (v.contains("(CRO)")){
                              //  System.out.println(v);
                                Importazioni.GiacenzeCRO_Sistema(v, c, progress);
                            }
            //Mappa_Wallet.put(v[3], v[1]);
        }
             //   Importazioni.GiacenzeCRO_Sistema("0x7bfa44a6dad637e8416eabe568c285cc94c7e7a7", c, progress);//da gestire il wallet
                progress.dispose();
                //in teoria dovrei trovarli e gestirli in automatico
                //in qualche variabile dovrei avere l'elenco dei wallet da cui estrarre solo quelli su rete CRO
            }
         };
        progress.SetThread(thread);
        thread.start();
        progress.setVisible(true);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        PopolaTabella();
    }//GEN-LAST:event_formWindowOpened

    private void Bottone_RimuoviChiaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_RimuoviChiaveActionPerformed
        // TODO add your handling code here:
              
        
        
        /*if (TabellaWallets.getSelectedRow() >= 0) {
            int rigaselezionata = TabellaWallets.getRowSorter().convertRowIndexToModel(TabellaWallets.getSelectedRow());

            String IDWallet = TabellaWallets.getModel().getValueAt(rigaselezionata, 1).toString();
            if (IDWallet != null) {
                
                 int r= JOptionPane.showConfirmDialog(this, "Attenzione! \nSei sicuro di voler eliminare il wallet \n"
                         + IDWallet+" ?",
                            "Wallet non Valido",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,null);
                 IDWallet=IDWallet+"_"+TabellaWallets.getModel().getValueAt(rigaselezionata, 2).toString();
              //  System.out.println(r);
                if(r==0){
                DatabaseH2.Pers_Wallets_Cancella(IDWallet);
                //ScriviFileWallets();
                PopolaTabella();
                String Messaggio = "Il Wallet è stato cancellato \nVuoi cancellare anche tutte le movimentazioni importate finora?";
            r=JOptionPane.showOptionDialog(this, Messaggio, "Cancellazione Transazioni Crypto", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"SI","NO"}, "OK");
           if(r==0){
               //Sicome devo mettere dei limiti di data metto l'anno 2100 come limite superiore e zero (1970) come limite inferiore
             //  long Data2100=Long.parseLong("4105615230000");
             int movEliminati=Funzioni.CancellaMovimentazioniXWallet(IDWallet.split("_")[0].trim()+" ("+IDWallet.split("_")[1].trim()+")",0,0);
             if (movEliminati>0){
                 CDC_Grafica.TabellaCryptodaAggiornare=true;
                 Messaggio="Numero movimenti cancellati : "+movEliminati+ "\n Ricordarsi di Salvare per non perdere le modifiche fatte sui movimenti.";
                JOptionPane.showOptionDialog(this,Messaggio, "Cancellazione Transazioni Crypto", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"OK"}, "OK");
                //Calcoli_Plusvalenze.AggiornaPlusvalenze();
                }
           }
           
                }
            }
        }else
           {
            JOptionPane.showConfirmDialog(this, "Attenzione! \nDevi selezionare un Wallet per poterlo eliminare",
                            "Nessun Wallet selezionato",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,null);    
           } */
                
                
                
                
    }//GEN-LAST:event_Bottone_RimuoviChiaveActionPerformed

    private void Bottone_AggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AggiornaActionPerformed
        // TODO add your handling code here:
      //  AggiornaWallets(null);
        
    }//GEN-LAST:event_Bottone_AggiornaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       // TransazioniCrypto_Funzioni_AggiornaPlusvalenze();
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void Bottone_AggiornaSelezionatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AggiornaSelezionatiActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = TabellaWallets.getSelectedRows();
        if (selectedRows.length == 0) {
            //System.out.println("Nessuna riga selezionata.");
            return;
            }
        TableModel model = TabellaWallets.getModel();
        
        for (int viewRow : selectedRows) {
            int modelRow = TabellaWallets.convertRowIndexToModel(viewRow);

            
            long data=Long.parseLong("1483228800000");
            String wallet = model.getValueAt(modelRow, 1).toString(); // 1 = seconda colonna
            String ApiKey = model.getValueAt(modelRow, 2).toString(); // 1 = seconda colonna
            String ApiSecret = model.getValueAt(modelRow, 3).toString(); // 1 = seconda colonna
            //come data di inizio metto la data dell'ulti movimento + 1 secondo
            if (!model.getValueAt(modelRow, 4).toString().equals("0"))
                data = OperazioniSuDate.ConvertiDatainLongSecondo(model.getValueAt(modelRow, 4).toString())+1000; // 1 = seconda colonna
            
           CcxtInterop.fetchMovimentiConBar(wallet, ApiKey, ApiSecret, data,"",this);
         /*  System.out.println(wallet);
           System.out.println(ApiKey);
           System.out.println(ApiSecret);
           System.out.println(data);*/
            
            

        }
        //AggiornaWallets(selezionati);
     
    }//GEN-LAST:event_Bottone_AggiornaSelezionatiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioneWallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestioneWallets().setVisible(true);
            }
        });
    }

    
    public static void LeggiFileWallets() {

            //Il file wallet è così composto
            //IndirizzoWallet;Rete;
            //la mappa che andrò a generare invece sarà
            //key:IndirizzoWallet_Rete
            //Dati:IndirizzoWallet;Rete
            File file = new File("Wallets.db");
          /*  if (!file.exists()) {
                //Se il file non esiste adesso lo creo ma successivamente non lo farò più, i dati verranno infatti messi nel database
                file.createNewFile();
            }*/
            if (file.exists()) {
                //Se il file esiste recupero i dati e lo metto nel database
                //successivamente leggerò i dati dal database
                String riga;
                try (FileReader fire = new FileReader("Wallets.db"); BufferedReader bure = new BufferedReader(fire);) {
                    while ((riga = bure.readLine()) != null) {
                        String rigaSplittata[] = riga.split(";");
                        if (rigaSplittata.length == 2) {
                            DatabaseH2.Pers_Wallets_Scrivi(rigaSplittata[0], rigaSplittata[1]);
                        }
                    }     
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GestioneWallets.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(GestioneWallets.class.getName()).log(Level.SEVERE, null, ex);
                }
                //A questo punto devo cancellare il file, ho salvato tutto nel database
                file.delete();

            }
            
            //Leggo i dati dal database
        //    MappaWallets=DatabaseH2.Pers_Wallets_LeggiTabella();
            

       
    }
    
    
  /*  static void ScriviFileWallets() {
   try { 
       FileWriter w=new FileWriter("Wallets.db");
       BufferedWriter b=new BufferedWriter (w);
       for (String k:MappaWallets.values()){
           b.write(k+"\n");
       }
       b.close();
       w.close();

    }catch (IOException ex) {
                 //  Logger.getLogger(AWS.class.getName()).log(Level.SEVERE, null, ex);
               }
   
   }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Aggiorna;
    private javax.swing.JButton Bottone_AggiornaSelezionati;
    private javax.swing.JButton Bottone_InserisciChiave;
    private javax.swing.JButton Bottone_RimuoviChiave;
    private javax.swing.JComboBox<String> ComboBox_Exchange;
    private javax.swing.JLabel Label_Exchange;
    private javax.swing.JLabel Label_IndirizzoWallet;
    private javax.swing.JLabel Label_IndirizzoWallet1;
    private javax.swing.JPanel Pannello_Chiavi;
    private javax.swing.JScrollPane ScrollPaneTabellaWallets;
    private javax.swing.JTable TabellaWallets;
    private javax.swing.JTextField TextField_ApiKey;
    private javax.swing.JTextField TextField_ApiSecret;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
