package com.giacenzecrypto.giacenze_crypto;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * Parte grafica della gestione documentale: elenca i file da cui i movimenti sono stati importati, con
 * quanti movimenti vi sono agganciati oggi, su quali wallet e in che periodo, e permette di aprirne una
 * copia, di esportarli decompressi e di eliminare quelli a cui non punta più nessun movimento.
 *
 * <p>È un {@link javax.swing.JPanel} e non una finestra perché viene montato in <b>due</b> posti: nel tab
 * "Gestione Documentale" di {@code Principale} e, a richiesta, dentro il dialogo {@link GUI_DocumentiFonte}.
 * Tenerne una sola copia è il motivo dell'estrazione: layout, colonne e regole di abilitazione dei pulsanti
 * esistono una volta sola.
 *
 * <p>La logica operativa resta in {@link Principale_DocumentiFonte}: qui ci sono solo il popolamento della
 * tabella e l'abilitazione dei pulsanti.
 *
 * <p>Due conseguenze dell'essere un pannello anziché un dialogo, entrambe visibili qui sotto :
 * <ul>
 *   <li>la finestra a cui agganciare i messaggi non si può memorizzare nel costruttore — quando
 *       {@code Principale.initComponents()} costruisce il pannello non esiste ancora un antenato — e va
 *       quindi risolta ogni volta con {@link #Proprietario()};</li>
 *   <li>il pulsante <i>Chiudi</i> ha senso solo nel dialogo, quindi parte nascosto e lo si accende con
 *       {@link #ImpostaAzioneChiusura(Runnable)}. Il pulsante resta comunque nel {@code .form}, così il
 *       layout continua a essere quello disegnato dal GUI Builder e non ne esistono due versioni.</li>
 * </ul>
 */
public class GUI_DocumentiFonte_Pannello extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Indice della colonna "Movimenti", quella che decide se un documento sia eliminabile.
     * <p>La costante è quella di {@link Principale_DocumentiFonte}, che è anche chi riempie le righe:
     * tenerne due copie significherebbe poterle disallineare.
     */
    private static final int COL_MOVIMENTI = Principale_DocumentiFonte.COLONNA_MOVIMENTI;

    /** Cosa fare quando si preme "Chiudi"; {@code null} finché nessuno lo chiede, e il pulsante resta nascosto */
    private Runnable AzioneChiusura = null;

    /** {@code true} se da quando il pannello è aperto è stato eliminato qualche documento */
    private boolean Modificato = false;

    /** Crea il pannello e lo riempie. */
    public GUI_DocumentiFonte_Pannello() {
        initComponents();

        Tabelle.Tabelle_ApplicaHeaderBoldCentrato(Tabella);
        //Righe alternate che seguono il tema chiaro/scuro. Va installato prima del primo Ricarica() :
        //AdattaLarghezzaColonne() misura le celle con prepareRenderer, quindi con il renderer che
        //sarà davvero in uso.
        Tabelle.ColoraTabellaSemplice(Tabella);

        //L'abilitazione dei pulsanti segue la selezione. Il listener resta scritto a mano: il GUI Builder
        //non modella gli eventi del modello di selezione di una JTable.
        Tabella.getSelectionModel().addListSelectionListener(e -> AggiornaStatoPulsanti());

        //Chi monta il pannello in un dialogo lo accende con ImpostaAzioneChiusura : in un tab non c'è
        //niente da chiudere.
        Bottone_Chiudi.setVisible(false);

        Ricarica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane_Tabella = new javax.swing.JScrollPane();
        Tabella = new javax.swing.JTable();
        Label_Riepilogo = new javax.swing.JLabel();
        Bottone_Apri = new javax.swing.JButton();
        Bottone_Esporta = new javax.swing.JButton();
        Bottone_Elimina = new javax.swing.JButton();
        Bottone_Aggiorna = new javax.swing.JButton();
        Bottone_Chiudi = new javax.swing.JButton();

        Tabella.setAutoCreateRowSorter(true);
        Tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Documento", "Tipo", "Origine", "Importato il", "Dimensione", "Su disco", "Movimenti", "Wallet / Exchange", "Periodo dei movimenti"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane_Tabella.setViewportView(Tabella);

        Bottone_Apri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Documento.png"))); // NOI18N
        Bottone_Apri.setText("Apri una copia");
        Bottone_Apri.setToolTipText("Il documento è conservato compresso: viene scompattata una copia nella cartella Temporanei e aperta quella, così l'originale non è modificabile");
        Bottone_Apri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_ApriActionPerformed(evt);
            }
        });

        Bottone_Esporta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Esporta.setText("Esporta selezionati...");
        Bottone_Esporta.setToolTipText("Scrive i documenti selezionati, decompressi, in una cartella a scelta");
        Bottone_Esporta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_EsportaActionPerformed(evt);
            }
        });

        Bottone_Elimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Cestino.png"))); // NOI18N
        Bottone_Elimina.setText("Elimina");
        Bottone_Elimina.setToolTipText("Possibile solo sui documenti a cui non è agganciato più nessun movimento");
        Bottone_Elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_EliminaActionPerformed(evt);
            }
        });

        Bottone_Aggiorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Aggiorna.png"))); // NOI18N
        Bottone_Aggiorna.setText("Aggiorna");
        Bottone_Aggiorna.setToolTipText("Rilegge il registro e ricalcola i movimenti agganciati");
        Bottone_Aggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AggiornaActionPerformed(evt);
            }
        });

        Bottone_Chiudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Annulla.png"))); // NOI18N
        Bottone_Chiudi.setText("Chiudi");
        Bottone_Chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_ChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_Tabella, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Riepilogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bottone_Apri, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Esporta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Aggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Chiudi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane_Tabella, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Riepilogo)
                    .addComponent(Bottone_Apri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Esporta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Aggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Chiudi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone_ApriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_ApriActionPerformed
        List<Integer> ids = IdSelezionati();
        if (ids.size() == 1) {
            Principale_DocumentiFonte.ApriDocumento(ids.get(0), Proprietario());
        }
    }//GEN-LAST:event_Bottone_ApriActionPerformed

    private void Bottone_EsportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_EsportaActionPerformed
        if (Principale_DocumentiFonte.EsportaDocumenti(IdSelezionati(), Proprietario())) {
            Ricarica();
        }
    }//GEN-LAST:event_Bottone_EsportaActionPerformed

    private void Bottone_EliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_EliminaActionPerformed
        if (Principale_DocumentiFonte.EliminaDocumenti(IdSelezionati(), Proprietario())) {
            Modificato = true;
            Ricarica();
        }
    }//GEN-LAST:event_Bottone_EliminaActionPerformed

    private void Bottone_AggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AggiornaActionPerformed
        Ricarica();
    }//GEN-LAST:event_Bottone_AggiornaActionPerformed

    private void Bottone_ChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_ChiudiActionPerformed
        if (AzioneChiusura != null) {
            AzioneChiusura.run();
        }
    }//GEN-LAST:event_Bottone_ChiudiActionPerformed

    /**
     * Rende visibile il pulsante "Chiudi" e gli assegna cosa fare.
     * <p>Da chiamare solo da chi monta il pannello in una finestra propria : in un tab il pulsante resta
     * nascosto, e {@code GroupLayout} non gli riserva spazio.
     *
     * @param Azione cosa eseguire alla pressione, tipicamente la chiusura della finestra ospite
     */
    public void ImpostaAzioneChiusura(Runnable Azione) {
        AzioneChiusura = Azione;
        Bottone_Chiudi.setVisible(Azione != null);
    }

    /** @return {@code true} se da quando il pannello esiste sono stati eliminati dei documenti */
    public boolean Modificato() {
        return Modificato;
    }

    /** @return il modello della tabella, creato nel form */
    private DefaultTableModel Modello() {
        return (DefaultTableModel) Tabella.getModel();
    }

    /**
     * La finestra a cui agganciare dialoghi e messaggi.
     * <p>Va risolta a ogni chiamata e non memorizzata nel costruttore : montato dentro un tab, il pannello
     * viene costruito da {@code Principale.initComponents()} quando un antenato ancora non c'è.
     *
     * @return la finestra che contiene il pannello, {@code null} se non è ancora agganciato
     */
    private Window Proprietario() {
        return SwingUtilities.getWindowAncestor(this);
    }

    /** Ricostruisce la tabella dal registro e dai movimenti attualmente in mappa. */
    public void Ricarica() {
        //Il cursore di attesa va messo sulla finestra, altrimenti copre solo l'area del pannello; finché
        //il pannello non è agganciato a nulla si ripiega su sé stesso.
        Component c = Proprietario() != null ? Proprietario() : this;
        c.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            Modello().setRowCount(0);
            List<Object[]> righe = Principale_DocumentiFonte.RigheDiRiepilogo();
            for (Object[] r : righe) {
                Modello().addRow(r);
            }
            Label_Riepilogo.setText(Principale_DocumentiFonte.TestoRiepilogo(righe));
            AdattaLarghezzaColonne();
        } finally {
            c.setCursor(Cursor.getDefaultCursor());
        }
        AggiornaStatoPulsanti();
    }

    /**
     * Porta ogni colonna alla larghezza del suo contenuto più lungo.
     * <p>La tabella è a {@code AUTO_RESIZE_OFF} perché l'elenco dei wallet e il nome dei documenti possono
     * essere lunghi: meglio uno scorrimento orizzontale che dieci colonne tutte troncate.
     */
    private void AdattaLarghezzaColonne() {
        for (int c = 0; c < Tabella.getColumnCount(); c++) {
            int larghezza = Tabella.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(Tabella, Modello().getColumnName(c), false, false, 0, c)
                    .getPreferredSize().width;
            for (int r = 0; r < Tabella.getRowCount(); r++) {
                larghezza = Math.max(larghezza, Tabella.prepareRenderer(Tabella.getCellRenderer(r, c), r, c)
                        .getPreferredSize().width);
            }
            Tabella.getColumnModel().getColumn(c).setPreferredWidth(Math.min(larghezza + 20, 400));
        }
    }

    /** @return gli id dei documenti selezionati, nell'ordine in cui compaiono nella tabella */
    private List<Integer> IdSelezionati() {
        List<Integer> ids = new ArrayList<>();
        for (int riga : Tabella.getSelectedRows()) {
            ids.add((Integer) Modello().getValueAt(Tabella.convertRowIndexToModel(riga), 0));
        }
        return ids;
    }

    /** @return {@code true} se ogni documento selezionato non ha più movimenti agganciati */
    private boolean TuttiSenzaMovimenti() {
        for (int riga : Tabella.getSelectedRows()) {
            if ((Integer) Modello().getValueAt(Tabella.convertRowIndexToModel(riga), COL_MOVIMENTI) > 0) {
                return false;
            }
        }
        return true;
    }

    private void AggiornaStatoPulsanti() {
        int selezionati = Tabella.getSelectedRowCount();
        //"Apri" lavora sul singolo: aprire dieci file insieme non è quello che si intende chiedendolo
        Bottone_Apri.setEnabled(selezionati == 1);
        Bottone_Esporta.setEnabled(selezionati > 0);
        Bottone_Elimina.setEnabled(selezionati > 0 && TuttiSenzaMovimenti());
        Bottone_Elimina.setToolTipText(selezionati > 0 && !TuttiSenzaMovimenti()
                ? "La selezione contiene documenti a cui sono ancora agganciati dei movimenti"
                : "Possibile solo sui documenti a cui non è agganciato più nessun movimento");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Aggiorna;
    private javax.swing.JButton Bottone_Apri;
    private javax.swing.JButton Bottone_Chiudi;
    private javax.swing.JButton Bottone_Elimina;
    private javax.swing.JButton Bottone_Esporta;
    private javax.swing.JLabel Label_Riepilogo;
    private javax.swing.JScrollPane ScrollPane_Tabella;
    private javax.swing.JTable Tabella;
    // End of variables declaration//GEN-END:variables
}
