/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.giacenzecrypto.giacenze_crypto;

/**
 * Dialogo dedicato per <b>aggiungere</b> o <b>modificare</b> una riga dell'anagrafica exchange
 * (id + nome). Sostituisce l'editing in cella di {@link GUI_AnagraficaExchange}.
 *
 * <p>{@link #confermato} dice al chiamante se leggere {@link #idRisultato} / {@link #nomeRisultato}.</p>
 */
public class GUI_ModificaExchange extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private final boolean inserimento;

    public boolean confermato = false;
    public String idRisultato = "";
    public String nomeRisultato = "";

    /**
     * @param owner finestra genitore per la modalità
     * @param id id esistente (in modifica, campo bloccato) oppure {@code null} per un nuovo exchange
     * @param nome nome esistente, o {@code null}
     */
    public GUI_ModificaExchange(java.awt.Window owner, String id, String nome) {
        super(owner, ModalityType.APPLICATION_MODAL);
        this.inserimento = id == null || id.isBlank();
        try {
            setIconImage(new javax.swing.ImageIcon(VarStatiche.getPathRisorse() + "logo.png").getImage());
        } catch (RuntimeException ignore) {
        }
        initComponents();

        setTitle(inserimento ? "Nuovo exchange" : "Modifica exchange");
        Campo_Id.setText(id == null ? "" : id);
        Campo_Id.setEnabled(inserimento);
        Campo_Nome.setText(nome == null ? "" : nome);
        getRootPane().setDefaultButton(Bottone_Ok);
        pack();
        setLocationRelativeTo(owner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Pannello_Campi = new javax.swing.JPanel();
        Label_Id = new javax.swing.JLabel();
        Campo_Id = new javax.swing.JTextField();
        Label_Nome = new javax.swing.JLabel();
        Campo_Nome = new javax.swing.JTextField();
        Pannello_Pulsanti = new javax.swing.JPanel();
        Bottone_Ok = new javax.swing.JButton();
        Bottone_Annulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifica exchange");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        Pannello_Campi.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 8, 12));
        Pannello_Campi.setLayout(new java.awt.GridBagLayout());

        Label_Id.setText("Identificativo (es. \"binance\") :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_Id, gridBagConstraints);

        Campo_Id.setColumns(18);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Campo_Id, gridBagConstraints);

        Label_Nome.setText("Nome (marchio) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        Pannello_Campi.add(Label_Nome, gridBagConstraints);

        Campo_Nome.setColumns(24);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        Pannello_Campi.add(Campo_Nome, gridBagConstraints);

        getContentPane().add(Pannello_Campi, java.awt.BorderLayout.CENTER);

        Pannello_Pulsanti.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        Pannello_Pulsanti.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        Bottone_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Ok.setText("OK");
        Bottone_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_OkActionPerformed(evt);
            }
        });
        Pannello_Pulsanti.add(Bottone_Ok);

        Bottone_Annulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Annulla.png"))); // NOI18N
        Bottone_Annulla.setText("Annulla");
        Bottone_Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AnnullaActionPerformed(evt);
            }
        });
        Pannello_Pulsanti.add(Bottone_Annulla);

        getContentPane().add(Pannello_Pulsanti, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_OkActionPerformed
        String id = Campo_Id.getText().trim().toLowerCase();
        String nome = Campo_Nome.getText().trim();
        if (inserimento && id.isEmpty()) {
            Messaggi.WarningMessage("Campo non valido", "L'identificativo non può essere vuoto.", this);
            return;
        }
        idRisultato = id;
        nomeRisultato = nome;
        confermato = true;
        dispose();
    }//GEN-LAST:event_Bottone_OkActionPerformed

    private void Bottone_AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AnnullaActionPerformed
        dispose();
    }//GEN-LAST:event_Bottone_AnnullaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Annulla;
    private javax.swing.JButton Bottone_Ok;
    private javax.swing.JTextField Campo_Id;
    private javax.swing.JTextField Campo_Nome;
    private javax.swing.JLabel Label_Id;
    private javax.swing.JLabel Label_Nome;
    private javax.swing.JPanel Pannello_Campi;
    private javax.swing.JPanel Pannello_Pulsanti;
    // End of variables declaration//GEN-END:variables
}
