/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.giacenzecrypto.giacenze_crypto;


import com.toedter.calendar.JTextFieldDateEditor;
import static com.giacenzecrypto.giacenze_crypto.Principale.MappaCryptoWallet;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static com.giacenzecrypto.giacenze_crypto.Principale.Mappa_Wallets_e_Dettagli;
import java.awt.Component;
import javax.swing.SwingWorker;

/**
 *
 * @author luca.passelli
 */
public class GUI_ModificaMovimento extends javax.swing.JDialog {
private static final long serialVersionUID = 9L;
    /**
     * Creates new form MovimentoManuale_GUI
     */
    //Map<String, List<String>> Wallets_e_Dettagli = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    String IDNuovo="";
    transient List<String> Lista_Cryptovalute = new ArrayList<>();
    transient List<String> Lista_NFT = new ArrayList<>();
    transient List<String> Lista_FIAT = new ArrayList<>();
    boolean ModificaMovimento=false;
    String MovimentoRiportato[]=new String[Importazioni.ColonneTabella];
    String MonetaE="";
    String MonetaU="";
    String MonetaETipo="";
    String MonetaUTipo="";
    String MonetaUAddress="";
    String MonetaEQta="";
    String MonetaEAddress="";
    String MonetaUQta="";
    String ValoreTransazione="";
    String Wallet="";
    String WalletDettaglio="";
   // String TipoMovimentoAM="M";//M se è un movimento inserito a mano, A se deriva da importazioni
   // String IDOriginale="";
    
    long DataLong=0;
    
    public GUI_ModificaMovimento() {
        setModalityType(ModalityType.APPLICATION_MODAL);
        initComponents();
        Bottone_Ok.setIcon(Icone.Salva);
        Bottone_Annulla.setIcon(Icone.Annulla);
        Bottone_ModificaPrezzo.setIcon(Icone.Euro);
        jButton1.setIcon(Icone.Unlock);
        ((JTextFieldDateEditor)Data_Datachooser.getDateEditor()).setBackground(Color.lightGray.brighter());
        
        //questo serve affinchè succeda qualcosa quando scrivo nei combobox
         MonetaUscita_ComboBox.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                FiltraItemsComboBoxMonete(MonetaUscita_ComboBox,MonetaUscita_ComboBox.getEditor().getItem().toString(),MonetaUscitaTipo_ComboBox,true);
            }
        });
         MonetaEntrata_ComboBox.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                FiltraItemsComboBoxMonete(MonetaEntrata_ComboBox,MonetaEntrata_ComboBox.getEditor().getItem().toString(),MonetaEntrataTipo_ComboBox,true);
            }
        });
                 
        this.setTitle("Inserimento Manuale Movimenti");
        ImageIcon icon = new ImageIcon(Statiche.getPathRisorse()+"logo.png");
        this.setIconImage(icon.getImage());
        //adesso recupero i vari wallet dalla lista e li metto nella combobox
        CreaMappeXComboBox();
        CompilaComboBoxWallet();
        //Compilo la mappa delle FIAT
        //Compilo la mappa delle Crypto
        //Compilo la mappa degli NFT
        
        
        //ora lancio EvidenziaProblemi che mi colora di giallo le parti da compilare
        EvidenziaProblemi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_Label = new javax.swing.JLabel();
        Data_Label = new javax.swing.JLabel();
        Data_Datachooser = new com.toedter.calendar.JDateChooser();
        Ora_Label = new javax.swing.JLabel();
        Ora_ComboBox = new javax.swing.JComboBox<>();
        Minuto_Label = new javax.swing.JLabel();
        Minuto_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscita_Label = new javax.swing.JLabel();
        MonetaEntrata_Label = new javax.swing.JLabel();
        MonetaUscitaTipo_Label = new javax.swing.JLabel();
        MonetaEntrataTipo_Label = new javax.swing.JLabel();
        MonetaEntrataTipo_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscitaTipo_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscitaQuantita_Label = new javax.swing.JLabel();
        MonetaUscitaQuantita_TextField = new javax.swing.JTextField();
        MonetaEntrataQuantita_Label = new javax.swing.JLabel();
        MonetaEntrataQuantita_TextField = new javax.swing.JTextField();
        Freccia1_Label = new javax.swing.JLabel();
        Freccia2_Label = new javax.swing.JLabel();
        Freccia3_Label = new javax.swing.JLabel();
        Note_Label = new javax.swing.JLabel();
        Note_ScrollPane = new javax.swing.JScrollPane();
        Note_TextArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ValoreTransazione_Label = new javax.swing.JLabel();
        ValoreTransazione_TextField = new javax.swing.JTextField();
        Bottone_ModificaPrezzo = new javax.swing.JButton();
        Bottone_Ok = new javax.swing.JButton();
        Bottone_Annulla = new javax.swing.JButton();
        ID_TextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Wallet_Label = new javax.swing.JLabel();
        WalletDettaglio_Label = new javax.swing.JLabel();
        Wallet_ComboBox = new javax.swing.JComboBox<>();
        WalletDettaglio_ComboBox = new javax.swing.JComboBox<>();
        Secondo_Label = new javax.swing.JLabel();
        Secondo_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscita_ComboBox = new javax.swing.JComboBox<>();
        MonetaEntrata_ComboBox = new javax.swing.JComboBox<>();
        MonetaUscitaAddress_Label = new javax.swing.JLabel();
        MonetaUscitaAddress_TextField = new javax.swing.JTextField();
        MonetaEntrataAddress_Label = new javax.swing.JLabel();
        MonetaEntrataAddress_TextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        P_LabelFonte = new javax.swing.JLabel();
        P_LabelMoneta = new javax.swing.JLabel();
        P_LabelPU = new javax.swing.JLabel();
        P_LabelTimeFonte = new javax.swing.JLabel();
        P_TextFonte = new javax.swing.JTextField();
        P_TextMoneta = new javax.swing.JTextField();
        P_TextPU = new javax.swing.JTextField();
        P_TextTimeFonte = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ID_Label.setText("ID Transazione : ");

        Data_Label.setText("Data : ");

        Data_Datachooser.setDateFormatString("dd/MM/yyyy");
        Data_Datachooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Data_DatachooserPropertyChange(evt);
            }
        });

        Ora_Label.setText("Ora :");

        Ora_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        Ora_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Ora_ComboBoxItemStateChanged(evt);
            }
        });
        Ora_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ora_ComboBoxActionPerformed(evt);
            }
        });

        Minuto_Label.setText("Minuto :");

        Minuto_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        Minuto_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Minuto_ComboBoxItemStateChanged(evt);
            }
        });

        MonetaUscita_Label.setText("Moneta Uscita : ");

        MonetaEntrata_Label.setText("Moneta Entrata : ");

        MonetaUscitaTipo_Label.setText("Tipo Moneta Uscita : ");

        MonetaEntrataTipo_Label.setText("Tipo Moneta Entrata : ");

        MonetaEntrataTipo_ComboBox.setForeground(new java.awt.Color(51, 51, 51));
        MonetaEntrataTipo_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Crypto", "NFT", "FIAT" }));
        MonetaEntrataTipo_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonetaEntrataTipo_ComboBoxItemStateChanged(evt);
            }
        });

        MonetaUscitaTipo_ComboBox.setForeground(new java.awt.Color(51, 51, 51));
        MonetaUscitaTipo_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Crypto", "NFT", "FIAT" }));
        MonetaUscitaTipo_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonetaUscitaTipo_ComboBoxItemStateChanged(evt);
            }
        });

        MonetaUscitaQuantita_Label.setText("Quantità Uscita : ");

        MonetaUscitaQuantita_TextField.setForeground(new java.awt.Color(51, 51, 51));
        MonetaUscitaQuantita_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonetaUscitaQuantita_TextFieldActionPerformed(evt);
            }
        });
        MonetaUscitaQuantita_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MonetaUscitaQuantita_TextFieldKeyReleased(evt);
            }
        });

        MonetaEntrataQuantita_Label.setText("Quantità Entrata : ");

        MonetaEntrataQuantita_TextField.setForeground(new java.awt.Color(51, 51, 51));
        MonetaEntrataQuantita_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MonetaEntrataQuantita_TextFieldKeyReleased(evt);
            }
        });

        Freccia1_Label.setText("->");

        Freccia2_Label.setText("->");

        Freccia3_Label.setText("->");

        Note_Label.setText("Note : ");

        Note_TextArea.setColumns(20);
        Note_TextArea.setRows(5);
        Note_ScrollPane.setViewportView(Note_TextArea);

        ValoreTransazione_Label.setText("Valore Transazione in EURO : ");

        ValoreTransazione_TextField.setEditable(false);
        ValoreTransazione_TextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ValoreTransazione_TextField.setForeground(new java.awt.Color(51, 51, 51));
        ValoreTransazione_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ValoreTransazione_TextFieldKeyReleased(evt);
            }
        });

        Bottone_ModificaPrezzo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Prezzo.png"))); // NOI18N
        Bottone_ModificaPrezzo.setText("Modifica Prezzo");
        Bottone_ModificaPrezzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_ModificaPrezzoActionPerformed(evt);
            }
        });

        Bottone_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Ok.setText("OK");
        Bottone_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_OkActionPerformed(evt);
            }
        });

        Bottone_Annulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Annulla.png"))); // NOI18N
        Bottone_Annulla.setText("Annulla");
        Bottone_Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AnnullaActionPerformed(evt);
            }
        });

        ID_TextField.setEnabled(false);

        Wallet_Label.setText("Exchange / Wallet : ");

        WalletDettaglio_Label.setText("Dettagli Wallet : ");

        Wallet_ComboBox.setEditable(true);
        Wallet_ComboBox.setForeground(new java.awt.Color(51, 51, 51));
        Wallet_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wallet_ComboBoxActionPerformed(evt);
            }
        });

        WalletDettaglio_ComboBox.setEditable(true);
        WalletDettaglio_ComboBox.setForeground(new java.awt.Color(51, 51, 51));
        WalletDettaglio_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WalletDettaglio_ComboBoxActionPerformed(evt);
            }
        });

        Secondo_Label.setText("Secondo : ");

        Secondo_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        MonetaUscita_ComboBox.setEditable(true);
        MonetaUscita_ComboBox.setForeground(new java.awt.Color(51, 51, 51));
        MonetaUscita_ComboBox.setMaximumSize(new java.awt.Dimension(250, 250));
        MonetaUscita_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonetaUscita_ComboBoxItemStateChanged(evt);
            }
        });

        MonetaEntrata_ComboBox.setEditable(true);
        MonetaEntrata_ComboBox.setForeground(new java.awt.Color(51, 51, 51));
        MonetaEntrata_ComboBox.setMaximumSize(new java.awt.Dimension(250, 250));
        MonetaEntrata_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonetaEntrata_ComboBoxItemStateChanged(evt);
            }
        });

        MonetaUscitaAddress_Label.setText("Address Uscita :");

        MonetaEntrataAddress_Label.setText("Address Entrata :");

        jButton1.setText("Sblocca Modifiche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        P_LabelFonte.setText("Fonte Prezzo :");

        P_LabelMoneta.setText("Moneta di riferimento :");

        P_LabelPU.setText("Prezzo Unitario :");

        P_LabelTimeFonte.setText("Timestamp Fonte :");

        P_TextFonte.setEditable(false);

        P_TextMoneta.setEditable(false);

        P_TextPU.setEditable(false);

        P_TextTimeFonte.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MonetaUscitaTipo_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MonetaUscitaTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(MonetaUscita_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MonetaUscita_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(MonetaUscitaQuantita_Label)
                                            .addComponent(MonetaUscitaAddress_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MonetaUscitaQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MonetaUscitaAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Data_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Data_Datachooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Ora_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ora_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Minuto_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Minuto_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Secondo_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Secondo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Freccia2_Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Freccia3_Label)
                                            .addComponent(Freccia1_Label))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(MonetaEntrataAddress_Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MonetaEntrataAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(MonetaEntrata_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(MonetaEntrataQuantita_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(MonetaEntrataTipo_Label, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(MonetaEntrataTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MonetaEntrataQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(MonetaEntrata_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(12, 12, 12))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ID_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_TextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Wallet_Label)
                            .addComponent(WalletDettaglio_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wallet_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WalletDettaglio_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Bottone_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Annulla, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(P_LabelFonte)
                            .addComponent(ValoreTransazione_Label)
                            .addComponent(P_LabelMoneta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ValoreTransazione_TextField)
                            .addComponent(P_TextFonte, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P_TextMoneta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P_LabelPU, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(P_LabelTimeFonte, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(P_TextPU)
                                    .addComponent(P_TextTimeFonte, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bottone_ModificaPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Note_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(Note_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_Label)
                    .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Data_Label)
                    .addComponent(Data_Datachooser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ora_Label)
                        .addComponent(Ora_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Minuto_Label)
                        .addComponent(Minuto_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Secondo_Label)
                        .addComponent(Secondo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wallet_Label)
                    .addComponent(Wallet_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WalletDettaglio_Label)
                    .addComponent(WalletDettaglio_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Freccia1_Label)
                    .addComponent(MonetaUscitaTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonetaUscitaTipo_Label)
                    .addComponent(MonetaEntrataTipo_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonetaEntrataTipo_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Freccia2_Label)
                    .addComponent(MonetaEntrata_Label)
                    .addComponent(MonetaUscita_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonetaEntrata_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonetaUscita_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MonetaEntrataQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MonetaEntrataQuantita_Label)
                        .addComponent(Freccia3_Label))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MonetaUscitaQuantita_Label)
                        .addComponent(MonetaUscitaQuantita_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MonetaEntrataAddress_Label)
                        .addComponent(MonetaEntrataAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MonetaUscitaAddress_Label)
                    .addComponent(MonetaUscitaAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValoreTransazione_Label)
                    .addComponent(ValoreTransazione_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_ModificaPrezzo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_LabelFonte)
                    .addComponent(P_LabelPU)
                    .addComponent(P_TextFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_TextPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_LabelMoneta)
                    .addComponent(P_LabelTimeFonte)
                    .addComponent(P_TextMoneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_TextTimeFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Note_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Note_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bottone_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Annulla, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreaMappeXComboBox(){
      //          Wallets_e_Dettagli = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
                Lista_FIAT.add("EUR");
          for (String[] v : MappaCryptoWallet.values()) {
              //PARTE 1: Recupero Wallet e dettagli del wallet
    /*          String WalletTemp=v[3];
              String WalletDettaglioTemp=v[4];
              if(Wallets_e_Dettagli.get(v[3])==null)
                  {
                      List<String> Lista=new ArrayList();
                      Lista.add(WalletDettaglioTemp);
                      Wallets_e_Dettagli.put(WalletTemp, Lista);
                  }
              else{
                  List<String> Lista;
                  Lista=Wallets_e_Dettagli.get(WalletTemp);
                  if (!Lista.contains(WalletDettaglioTemp))Lista.add(WalletDettaglioTemp);
              }*/
              //Parte 2 recupero della lista delle crypto, lista nft etc...
              String TipoUscita=v[9];
              String MonetaUscita=v[8];
              String TipoEntrata=v[12];
              String MonetaEntrata=v[11];
              //qui elenco le monete in uscita
              if (TipoUscita.equalsIgnoreCase("Crypto")){                 
                  if(!Lista_Cryptovalute.contains(MonetaUscita))Lista_Cryptovalute.add(MonetaUscita);
                 // Mappa_Cryptovalute.put(MonetaUscita, MonetaUscita);
              }else if (TipoUscita.equalsIgnoreCase("NFT")){
                  if(!Lista_NFT.contains(MonetaUscita))Lista_NFT.add(MonetaUscita);
                //  Mappa_NFT.put(MonetaUscita, MonetaUscita);
              }else if (TipoUscita.equalsIgnoreCase("FIAT")){
                  if(!Lista_FIAT.contains(MonetaUscita))Lista_FIAT.add(MonetaUscita);
                 // Mappa_FIAT.put(MonetaUscita, MonetaUscita);
              }
              //qui quelle in entrata mettendole ovviamente nella stessa mappa chemi servirà solo per avere poi l'elenco
              if (TipoEntrata.equalsIgnoreCase("Crypto")){
                  if(!Lista_Cryptovalute.contains(MonetaEntrata))Lista_Cryptovalute.add(MonetaEntrata);
                //  Mappa_Cryptovalute.put(MonetaEntrata, MonetaEntrata);
              }else if (TipoEntrata.equalsIgnoreCase("NFT")){
                  if(!Lista_NFT.contains(MonetaEntrata))Lista_NFT.add(MonetaEntrata);
                //  Mappa_NFT.put(MonetaEntrata, MonetaEntrata);
              }else if (TipoEntrata.equalsIgnoreCase("FIAT")){
                  if(!Lista_FIAT.contains(MonetaEntrata))Lista_FIAT.add(MonetaEntrata);
                //  Mappa_FIAT.put(MonetaEntrata, MonetaEntrata);
              }
              Collections.sort(Lista_Cryptovalute);
              Collections.sort(Lista_NFT);
              Collections.sort(Lista_FIAT);
          }
    }
    
 
    
        private void FiltraItemsComboBoxMonete(JComboBox<String> combobox,String filter,JComboBox<String> comboboxTipo,boolean apriMenu) {
        String Tipo=comboboxTipo.getSelectedItem().toString();
        List<String> Lista=new ArrayList<>();
        if (Tipo.equalsIgnoreCase("Crypto")) {
            Lista=Lista_Cryptovalute;
        } else if (Tipo.equalsIgnoreCase("NFT")) {
            Lista=Lista_NFT;
        } else if (Tipo.equalsIgnoreCase("FIAT")) {
            Lista=Lista_FIAT;
        }
        combobox.setPopupVisible(false);
        combobox.removeAllItems();
        combobox.addItem(filter);
        for (String item : Lista) {
            if (item.toLowerCase().contains(filter.toLowerCase())) {
                if(!filter.equals(item))combobox.addItem(item);
            }
        }       
        if (apriMenu)combobox.setPopupVisible(true);
    }
        
   /* private void FiltraItemsComboBoxWallet(JComboBox combobox,String filter,JComboBox comboboxTipo,boolean apriMenu) {
        String Tipo=comboboxTipo.getSelectedItem().toString();
        List<String> Lista=new ArrayList<>();
        if (Tipo.equalsIgnoreCase("Crypto")) {
            Lista=Lista_Cryptovalute;
        } else if (Tipo.equalsIgnoreCase("NFT")) {
            Lista=Lista_NFT;
        } else if (Tipo.equalsIgnoreCase("FIAT")) {
            Lista=Lista_FIAT;
        }
        combobox.setPopupVisible(false);
        combobox.removeAllItems();
        combobox.addItem(filter);
        for (String item : Lista) {
            if (item.toLowerCase().contains(filter.toLowerCase())) {
                if(!filter.equals(item))combobox.addItem(item);
            }
        }       
        if (apriMenu)combobox.setPopupVisible(true);
    }*/
    
    private void MonetaUscitaQuantita_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonetaUscitaQuantita_TextFieldActionPerformed
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscitaQuantita_TextFieldActionPerformed

    private void Ora_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ora_ComboBoxActionPerformed
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_Ora_ComboBoxActionPerformed

    private void Bottone_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_OkActionPerformed
        // TODO add your handling code here:
        //Come prima cosa controllo che il prezzo sia congruo con quello in memoria
        //Quindi il prezzo della transazione deve essere uguale a quella calcolata partendo dal prezzo unitario preso dalla fonte.
        //Potrebbe infatti essere diverso nel momento in cui ambio un quantitativo dopo aver assegnato il prezzo.
        String PrezzoUnitario = P_TextPU.getText();
        String MonetaFonte = P_TextMoneta.getText();
        String ValoreTrans = ValoreTransazione_TextField.getText();
        String ValoreTransCalcolato = "";
        if (!MonetaFonte.isBlank() && !PrezzoUnitario.isBlank()) {
            if (MonetaFonte.equals(MonetaU)) {
                ValoreTransCalcolato = new BigDecimal(MonetaUQta).multiply(new BigDecimal(PrezzoUnitario)).abs().setScale(2, RoundingMode.HALF_UP).toPlainString();
            }
            if (MonetaFonte.equals(MonetaE)) {
                ValoreTransCalcolato = new BigDecimal(MonetaEQta).multiply(new BigDecimal(PrezzoUnitario)).abs().setScale(2, RoundingMode.HALF_UP).toPlainString();
            }

        }
        //Se il valore transcalcolato=blanc significa che non ho prezzi presi da una fonte quindi vado avanti
        if (!ValoreTransCalcolato.equals(ValoreTrans)&&!ValoreTransCalcolato.isBlank()) {
            //segnalo che il prezzo non è congruo e torno alla schermata del prezzo
            JOptionPane.showConfirmDialog(this, "Attenzione!\n"
                    + "Il prezzo imputato alla transazione non è corretto e congruo con la fonte scelta\n"
                    + "Modificare il prezzo della transazione.",
                    "Prezzo imputato non corretto", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null);
        } else {
            
            //Se arrivo qua vuol dire che il prezzo è congruo e finalizzo la transazione
            String ID = CalcolaID();
            ScritturaDati(ID);
        }
        
        
    }//GEN-LAST:event_Bottone_OkActionPerformed

    public void ScritturaDati(String ID){
    if(!EvidenziaProblemi()){
            //se non trovo problemi nella compilazione allora procedo con l'inserimento del movimento
            
            //prima cosa genero l'id della transazione
           // String ID=CalcolaID();
            System.out.println(ID);
            
            //verifico che non esista già una transazione non lo stesso id in quel caso chiedo se sovrascriverla o aggiungerla
            //per trovare l'id ovviamente devo cercarla nella mappa delle transazioni
            if(MappaCryptoWallet.get(ID)!=null && !ModificaMovimento){
              //se entro qua significa che ho già un movimento con lo stesso id 
              
              //provo a generare un nuovo ID aggiungendo 1 al penultimo campo
              String IDsplit[]=ID.split("_");
              if (Funzioni.isNumeric(IDsplit[IDsplit.length-2], false)){
                  //il nuovo valore sarà quello vecchio incrementato di 1
                  IDsplit[IDsplit.length-2]=String.valueOf(Long.parseLong(IDsplit[IDsplit.length-2])+1);
                  ID="";
                  for(String II:IDsplit){
                      ID=ID+II+"_";
                  }
                  ID=ID.substring(0, ID.length()-1);
                  ScritturaDati(ID);
              }
              //adesso devo far scegliere che fare
              //la cosa più semplice per ora è inserire un messaggio in cui si chiede di cambiare l'orario
              //o qualcosa del genere
             // System.out.println("ma va la");
              else JOptionPane.showConfirmDialog(this, "Attenzione!\nEsiste un movimento con lo stesso ID Transazione\nProvare a modificare l'ora della transazione anche di un solo secondo per risolvere il problema",
                    "Movimento con Stesso ID",JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE,null);
            }else{
              //se invece arrivo qua posso inserire il movimento nella mappa  
              if (ScriviMovimento(ID)){
                Principale.TabellaCryptodaAggiornare=true;
                this.dispose(); 
              }
            }
  
            
            
        }
    }
    
    
    public void CompilaCampidaID(String IDTransazione){
        try {
            String riga[]=Principale.MappaCryptoWallet.get(IDTransazione);
            MovimentoRiportato=riga;
            String DataOraMinutiSecondo=riga[0].split("_")[0];
            SimpleDateFormat f = new SimpleDateFormat("yyyyMMdd");
            Date d = f.parse(DataOraMinutiSecondo.substring(0,8));
            this.Data_Datachooser.setDate(d);
            this.Ora_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(8,10));
            this.Minuto_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(10,12));
            this.Secondo_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(12,14));
            this.ID_TextField.setText(riga[0]);
            this.Wallet_ComboBox.setSelectedItem(riga[3]);
            this.WalletDettaglio_ComboBox.setSelectedItem(riga[4]);
            this.MonetaUscitaTipo_ComboBox.setSelectedItem(riga[9]);
            this.MonetaUscita_ComboBox.setSelectedItem(riga[8]);
            this.MonetaUscitaQuantita_TextField.setText(riga[10]);
            this.MonetaUscitaAddress_TextField.setText(riga[26]);
            this.MonetaEntrataTipo_ComboBox.setSelectedItem(riga[12]);
            this.MonetaEntrata_ComboBox.setSelectedItem(riga[11]);
            this.MonetaEntrataQuantita_TextField.setText(riga[13]);
            this.MonetaEntrataAddress_TextField.setText(riga[28]);
            this.ValoreTransazione_TextField.setText(riga[15]);
            this.Note_TextArea.setText(riga[21].replace("<br>", "\n"));
            if(!riga[40].isBlank()){
                Prezzi.InfoPrezzo IP=new Prezzi.InfoPrezzo(riga[40]);
                if (IP.Moneta!=null)P_TextMoneta.setText(IP.Moneta);
                if (IP.Fonte!=null)P_TextFonte.setText(IP.Fonte);
                if (IP.prezzoUnitario!=null)this.P_TextPU.setText(IP.prezzoUnitario.toPlainString());
                if (IP.timestamp!=0)P_TextTimeFonte.setText(IP.RitornaStringData());
            }
//            TipoMovimentoAM=riga[22];
            //System.out.println(riga[22]);
            ModificaMovimento=true;
            //Adesso se è un movimento automatico do la possibilità di variarne solo il valore in euro
            //Altrimenti potrei dare la possibilità di variare tutto ma questo dovrebbe comportare  
            //che dovrò eseguire la cancellazione del vecchio elemento e l'inserimento del nuovo con un nuovo possibile IDTransazione
            //Per ora direi che è sufficiente dare la possibilita di variare i solo valore della transazione o le note
            //quindi
            if (!riga[22].equals("M")&&!riga[7].equalsIgnoreCase("Rettifica Automatica")) {
                this.Data_Datachooser.setEnabled(false);
                //this.Ora_ComboBox.setEnabled(false);
                //this.Minuto_ComboBox.setEnabled(false);
                //this.Secondo_ComboBox.setEnabled(false);
                this.ID_TextField.setEnabled(false);
                this.Wallet_ComboBox.setEnabled(false);
                this.WalletDettaglio_ComboBox.setEnabled(false);
                this.MonetaUscitaTipo_ComboBox.setEnabled(false);
                this.MonetaUscita_ComboBox.setEnabled(false);
                this.MonetaUscitaQuantita_TextField.setEnabled(false);
                this.MonetaUscitaAddress_TextField.setEnabled(false);
                this.MonetaEntrataTipo_ComboBox.setEnabled(false);
                this.MonetaEntrata_ComboBox.setEnabled(false);
                this.MonetaEntrataQuantita_TextField.setEnabled(false);
                this.MonetaEntrataAddress_TextField.setEnabled(false);
            }    
            
            EvidenziaProblemi();
        } catch (ParseException ex) {
            Logger.getLogger(GUI_ModificaMovimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        public void CompilaCampiPrincipalidaID(String IDTransazione){
        try {
            String riga[]=Principale.MappaCryptoWallet.get(IDTransazione);
            MovimentoRiportato=riga;
            String DataOraMinutiSecondo=riga[0].split("_")[0];
            SimpleDateFormat f = new SimpleDateFormat("yyyyMMdd");
            Date d = f.parse(DataOraMinutiSecondo.substring(0,8));
            this.Data_Datachooser.setDate(d);
            this.Ora_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(8,10));
            this.Minuto_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(10,12));
            this.Secondo_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(12,14));
            this.Wallet_ComboBox.setSelectedItem(riga[3]);
            this.WalletDettaglio_ComboBox.setSelectedItem(riga[4]);           
           // EvidenziaProblemi();
        } catch (ParseException ex) {
            Logger.getLogger(GUI_ModificaMovimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
            public void CompilaMovimentoOppostoID(String IDTransazione){
        try {
            String riga[]=Principale.MappaCryptoWallet.get(IDTransazione);
            MovimentoRiportato=riga;
            String DataOraMinutiSecondo=riga[0].split("_")[0];
            SimpleDateFormat f = new SimpleDateFormat("yyyyMMdd");
            Date d = f.parse(DataOraMinutiSecondo.substring(0,8));
            this.Data_Datachooser.setDate(d);
            this.Ora_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(8,10));
            this.Minuto_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(10,12));
            this.Secondo_ComboBox.setSelectedItem(DataOraMinutiSecondo.substring(12,14));
            //this.Wallet_ComboBox.setSelectedItem(riga[3]);
            //this.WalletDettaglio_ComboBox.setSelectedItem(riga[4]);
            this.MonetaEntrata_ComboBox.setSelectedItem(riga[8]);
            this.MonetaUscita_ComboBox.setSelectedItem(riga[11]);
            this.MonetaEntrataAddress_TextField.setText(riga[26]);
            this.MonetaUscitaAddress_TextField.setText(riga[28]);
            this.MonetaEntrataQuantita_TextField.setText(riga[10]);
            this.MonetaUscitaQuantita_TextField.setText(riga[13]);
            this.MonetaEntrataTipo_ComboBox.setSelectedItem(riga[9]);
            this.MonetaUscitaTipo_ComboBox.setSelectedItem(riga[12]);
            this.ValoreTransazione_TextField.setText(riga[15]);
           // EvidenziaProblemi();
        } catch (ParseException ex) {
            Logger.getLogger(GUI_ModificaMovimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    
    private void MonetaUscitaQuantita_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonetaUscitaQuantita_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscitaQuantita_TextFieldKeyReleased

    private void MonetaEntrataQuantita_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonetaEntrataQuantita_TextFieldKeyReleased
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaEntrataQuantita_TextFieldKeyReleased

    private void ValoreTransazione_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValoreTransazione_TextFieldKeyReleased
        // TODO add your handling code here:
       // EvidenziaProblemi();
    }//GEN-LAST:event_ValoreTransazione_TextFieldKeyReleased

    private void MonetaUscitaTipo_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonetaUscitaTipo_ComboBoxItemStateChanged
        // TODO add your handling code here:
        //Se cambio la tipologia per prima cosa carico la mappa per la combobox
       // this.CompilaComboBoxMoneteUscite();
        FiltraItemsComboBoxMonete(MonetaUscita_ComboBox,MonetaUscita_ComboBox.getEditor().getItem().toString(),MonetaUscitaTipo_ComboBox,false);
        //come seconda cosa faccio il controllo che tutto sia compilato correttamente
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscitaTipo_ComboBoxItemStateChanged

    private void MonetaEntrataTipo_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonetaEntrataTipo_ComboBoxItemStateChanged
        // TODO add your handling code here:
        //this.CompilaComboBoxMoneteEntrate();
        FiltraItemsComboBoxMonete(MonetaEntrata_ComboBox,MonetaEntrata_ComboBox.getEditor().getItem().toString(),MonetaEntrataTipo_ComboBox,false);
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaEntrataTipo_ComboBoxItemStateChanged

    private void Data_DatachooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Data_DatachooserPropertyChange
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_Data_DatachooserPropertyChange

    private void Wallet_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wallet_ComboBoxActionPerformed
        // TODO add your handling code here:
                //Se cambiano le proprietà di questo oggetto devo cambiare di conseguenza l'oggetto del dettaglio del wallet
        this.WalletDettaglio_ComboBox.removeAllItems();
        List<String> Dettagli = Mappa_Wallets_e_Dettagli.get(Wallet_ComboBox.getSelectedItem().toString());
        if (Dettagli != null) {
            this.WalletDettaglio_ComboBox.addItem("");
            for (String v : Dettagli) {
                this.WalletDettaglio_ComboBox.addItem(v);
            }
        }
        EvidenziaProblemi();
    }//GEN-LAST:event_Wallet_ComboBoxActionPerformed

    private void WalletDettaglio_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WalletDettaglio_ComboBoxActionPerformed
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_WalletDettaglio_ComboBoxActionPerformed

    private void Bottone_AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AnnullaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Bottone_AnnullaActionPerformed

    private void MonetaUscita_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonetaUscita_ComboBoxItemStateChanged
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaUscita_ComboBoxItemStateChanged

    private void MonetaEntrata_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonetaEntrata_ComboBoxItemStateChanged
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_MonetaEntrata_ComboBoxItemStateChanged

    private void Ora_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Ora_ComboBoxItemStateChanged
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_Ora_ComboBoxItemStateChanged

    private void Minuto_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Minuto_ComboBoxItemStateChanged
        // TODO add your handling code here:
        EvidenziaProblemi();
    }//GEN-LAST:event_Minuto_ComboBoxItemStateChanged

    private void Bottone_ModificaPrezzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_ModificaPrezzoActionPerformed
        // TODO add your handling code here:

        if (!EvidenziaProblemi()) {

            //Creo gli oggetti moneta
            Moneta MU = new Moneta();
            Moneta ME = new Moneta();
            MU.Moneta = this.MonetaU;
            MU.MonetaAddress = this.MonetaUAddress;
            MU.Qta = this.MonetaUQta;
            MU.Tipo = this.MonetaUTipo;
            ME.Moneta = this.MonetaE;
            ME.MonetaAddress = this.MonetaEAddress;
            ME.Qta = this.MonetaEQta;
            ME.Tipo = this.MonetaETipo;
            
            


            //Creo l'oggetto Infoprezzo
            BigDecimal PrezzoTot=BigDecimal.ZERO;
            if (Funzioni.isNumeric(this.ValoreTransazione, false)) {
               PrezzoTot=new BigDecimal(this.ValoreTransazione) ;
            }
            String Fonte = P_TextFonte.getText();
            String MonetaFonte = P_TextMoneta.getText();
            String PUnitario = P_TextPU.getText();
            String TimeSFonte = P_TextTimeFonte.getText();
            BigDecimal BD_PUnitario = null;
            if (Funzioni.isNumeric(PUnitario, false)) {
                BD_PUnitario = new BigDecimal(PUnitario);
            }
            long l_TimeStampFonte = 0;
            if (TimeSFonte!=null&&!TimeSFonte.isBlank()) {
                TimeSFonte=TimeSFonte.replaceAll("XX", "00");
                l_TimeStampFonte = FunzioniDate.ConvertiDatainLongSecondo(TimeSFonte);
            }
            Prezzi.InfoPrezzo IPr = new Prezzi.InfoPrezzo(BD_PUnitario, Fonte, l_TimeStampFonte, PrezzoTot, null, MonetaFonte);

            Component c = this;
            Download progress = new Download();
            progress.MostraProgressAttesa("Scaricamento Prezzi", "Attendi scaricamento dei prezzi...");
            progress.setLocationRelativeTo(this);
            String Ritorno[]=new String[2];
            //Oggetto 0 -> Prezzo
            //Oggetto 1 -> Token+"|"+TimeStamp+"|"+PrezzoU+"|"+Fonte;

            Thread thread;
            thread = new Thread() {
                public void run() {
                    String Rete=null;
                    if (ModificaMovimento) Rete=Funzioni.TrovaReteDaID(MovimentoRiportato[0]);
                    GUI_ModificaPrezzo t = new GUI_ModificaPrezzo(MU, ME,IPr,DataLong,Rete,Ritorno,progress);
                    //GUI_ModificaPrezzo t = new GUI_ModificaPrezzo(MU, ME,IPr,DataLong,Rete,Ritorno);
                    t.setLocationRelativeTo(c);
                    t.setVisible(true);
                    progress.ChiudiFinestra();
                }
            };
            thread.start();
            progress.setVisible(true);
           // progress.ChiudiFinestra();
           /* progress.setVisible(true);

SwingWorker<Void, Void> worker = new SwingWorker<>() {
    String rete;

    @Override
    protected Void doInBackground() throws Exception {
        if (ModificaMovimento) rete = Funzioni.TrovaReteDaID(MovimentoRiportato[0]);
        return null;
    }

    @Override
    protected void done() {
        progress.ChiudiFinestra();

        GUI_ModificaPrezzo dialog =
            new GUI_ModificaPrezzo(MU, ME, IPr, DataLong, rete, Ritorno, null);

        dialog.setLocationRelativeTo(c);

        // MODAL: qui si ferma finché non chiudi la finestra
        dialog.setVisible(true);

        System.out.println("Ritorno = " + Ritorno[0]);
    }
};

worker.execute();*/

            
            
            
            
            
            
            
            
            
            //Ora elaboro i dati in ritorno
            System.out.println(Ritorno[0]);
            if (Ritorno[0]!=null){
                //Ho il prezzo di ritorno
                if (Funzioni.isNumeric(Ritorno[0], false)){
                    ValoreTransazione_TextField.setText(Ritorno[0]);
                }else ValoreTransazione_TextField.setText("0.00");
            }
            if (Ritorno[1]!=null&&Ritorno[1].split("\\|",-1).length==4){
                //Ho i dettagli in ritorno
                Prezzi.InfoPrezzo IP=new Prezzi.InfoPrezzo(Ritorno[1]);
                if (IP.Fonte!=null) P_TextFonte.setText(IP.Fonte);else P_TextFonte.setText("");
                if (IP.Moneta!=null)P_TextMoneta.setText(IP.Moneta);else P_TextMoneta.setText("");
                if (IP.prezzoUnitario!=null)P_TextPU.setText(IP.prezzoUnitario.toPlainString());else P_TextPU.setText("");
                if (IP.timestamp!=0)P_TextTimeFonte.setText(IP.RitornaStringData());else P_TextTimeFonte.setText("");
                
            }
            
            //System.out.println(Ritorno[0]);
            
        }
   /*     String Rete=null;
        if (ModificaMovimento) Rete=Funzioni.TrovaReteDaID(MovimentoRiportato[0]);

       setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
       Moneta MonetaUscita=null;
       Moneta MonetaEntrata=null;
       if(!MonetaU.equalsIgnoreCase("")&&!MonetaUQta.equalsIgnoreCase("")&&MonetaUTipo!=null){
       MonetaUscita=new Moneta();
       MonetaUscita.Moneta=MonetaU;
       MonetaUscita.Qta=MonetaUQta;
       MonetaUscita.Tipo=MonetaUTipo;
       MonetaUscita.MonetaAddress=this.MonetaUAddress;

        }
       if(!MonetaE.equalsIgnoreCase("")&&!MonetaEQta.equalsIgnoreCase("")&&MonetaETipo!=null){
       MonetaEntrata=new Moneta();
       MonetaEntrata.Moneta=MonetaE;
       MonetaEntrata.Qta=MonetaEQta;
       MonetaEntrata.Tipo=MonetaETipo;
       MonetaEntrata.MonetaAddress=this.MonetaEAddress;

        }

       String Prezzo=Prezzi.DammiPrezzoTransazione(MonetaEntrata, MonetaUscita, DataLong, "0", true, 2, Rete,"binance");
        ValoreTransazione_TextField.setText(Prezzo);
       EvidenziaProblemi();
       setCursor(Cursor.getDefaultCursor());*/
 
    }//GEN-LAST:event_Bottone_ModificaPrezzoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Bottone_ModificaPrezzo.requestFocus();
        //Verifico se se è un movimento che è associato ad un altro movimento nel qual cosa avverto che per poter modificare il movimento bisogna 
        //prima eliminare le eventuali associazioni

        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Wallet_ComboBox.setEnabled(true);
        WalletDettaglio_ComboBox.setEnabled(true);
        this.Data_Datachooser.setEnabled(true);
        this.MonetaEntrataAddress_TextField.setEnabled(true);
        this.MonetaUscitaAddress_TextField.setEnabled(true);
        this.MonetaEntrataQuantita_TextField.setEnabled(true);
        this.MonetaUscitaQuantita_TextField.setEnabled(true);
        this.MonetaEntrata_ComboBox.setEnabled(true);
        this.MonetaUscita_ComboBox.setEnabled(true);
        this.MonetaEntrataTipo_ComboBox.setEnabled(true);
        this.MonetaUscitaTipo_ComboBox.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CompilaComboBoxWallet(){
        this.Wallet_ComboBox.removeAllItems();
        this.Wallet_ComboBox.addItem("");
        for (String v : Mappa_Wallets_e_Dettagli.keySet()) {
              this.Wallet_ComboBox.addItem(v);
          }
    }
    
    private String CompilaRiga40(){
    String TimeFonte=Prezzi.InfoPrezzo.ConvertiDataATimestamp(P_TextTimeFonte.getText());
        if (TimeFonte==null)TimeFonte="";  
        String Riga40="";
        if (!(P_TextMoneta.getText()+TimeFonte+P_TextPU.getText()+P_TextFonte.getText()).isBlank())
        {
            Riga40=(P_TextMoneta.getText()+"|"+TimeFonte+"|"+P_TextPU.getText()+"|"+P_TextFonte.getText());
        }
        return Riga40;
        
    }

    private boolean ScriviMovimento(String ID) {

        //questa è la funzione che si occuperà nello specifico di scrivere il movimento in ogni sua parte nella tabella
        
        String Riga40=CompilaRiga40();
        
        String Note = this.Note_TextArea.getText().replace(";", " ").replace("\n", "<br>");
        ValoreTransazione = new BigDecimal(ValoreTransazione).setScale(2, RoundingMode.HALF_UP).toString();
        MonetaUQta = MonetaUQta.replace("-", "");
        if (Funzioni.isNumeric(MonetaUQta, false) && !MonetaUQta.equalsIgnoreCase("0")) {
            MonetaUQta = "-" + MonetaUQta;
        }
        MonetaEQta = MonetaEQta.replace("-", "");
        boolean MovimentoValorizzato = false;

        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd ");
        String Data = f.format(Data_Datachooser.getDate())
                + Ora_ComboBox.getSelectedItem().toString() + ":"
                + Minuto_ComboBox.getSelectedItem().toString();

        String TipoTransazione = Importazioni.RitornaTipologiaTransazione(MonetaUTipo, MonetaETipo, 1);

      /*  String Rete = Funzioni.TrovaReteDaID(ID);
        if (ModificaMovimento&&Rete==null) Rete=Funzioni.TrovaReteDaIMovimento(MovimentoRiportato);*/

        //Se il prezzo scritto è zero controllo se i token hanno un valore, così non fosse chiedo all'utente se vuole confermare che il prezzo sia zero
        if (ValoreTransazione.equals("0.00")) {
            //Adesso prima di scrivere il movimento devo verificare se il movimento è valorizzato, se non lo è e non trovo prezzo per il token
            //chiedo all'utente se vuole confermare che il prezzo è zero e se conferma metto a SI la colonnina che dice se il prezzo è valorizzato
            Moneta MU ;
            Moneta ME ;
            if (!MonetaU.isEmpty()) {
                MU = new Moneta();
                MU.Moneta = this.MonetaU;
                MU.MonetaAddress = this.MonetaUAddress;
                MU.Qta = this.MonetaUQta;
                MU.Tipo = this.MonetaUTipo;
            }
            if (!MonetaE.isEmpty()) {
                ME = new Moneta();
                ME.Moneta = this.MonetaE;
                ME.MonetaAddress = this.MonetaEAddress;
                ME.Qta = this.MonetaEQta;
                ME.Tipo = this.MonetaETipo;
            }
           // long dataLong = FunzioniDate.ConvertiDatainLongMinuto(Data);
           // String Prezzo = Prezzi.DammiPrezzoTransazione(MU, ME, dataLong, null, true, 15, Rete,"");
            String Prezzo=ValoreTransazione_TextField.getText();
            if (Prezzo.equals("0.00")) {
                String Messaggio = "Attenzione, il prezzo del movimento è valorizzato a '0.00'.\n"
                        + "E' corretto e si vuole Proseguire?";
                int risposta = JOptionPane.showOptionDialog(this, Messaggio, "Conferma Prezzo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, "Si");
                //Si=0
                //No=1
                switch (risposta) {
                    case 0 -> {
                        MovimentoValorizzato = true;
                    }
                    case 1 -> {
                        JOptionPane.showConfirmDialog(this, "Operazione Annullata",
                                "Operazione Annullata", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
                        return false;
                    }
                    case -1 -> {
                        JOptionPane.showConfirmDialog(this, "Operazione Annullata",
                                "Operazione Annullata", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
                        return false;
                    }

                }
            } else {
                MovimentoValorizzato = true;
            }
        } else {
            MovimentoValorizzato = true;
        }

        if (MonetaETipo==null)MonetaETipo="";
        if (MonetaUTipo==null)MonetaUTipo="";
        
        if (ModificaMovimento) {
            String IDtsOri[] = MovimentoRiportato[0].split("_");
            String IDts[] = ID.split("_");
        //Se il tipo movinto del nuovo id è DC (Deposito Crypto)
        //Vedo se il tipo movimento vecchio era RW o TI e in quel caso cerco di usare lo stesso id che c'era prima
        //lo stesso vale se trovo altre movimentazioni analoghe
        //Cambierò eventialmente solo data e ora se queste sono cambiate
        
           // String IDTemp="";
           
           //Se stessa moneta u/e, stesso tipou/e,stesso wallet allora lo considero lo stesso movimento
            if (MovimentoRiportato[3].equals(Wallet) && MovimentoRiportato[4].equals(WalletDettaglio)
                    && MonetaU.trim().equals(MovimentoRiportato[8]) && MonetaE.trim().equals(MovimentoRiportato[11])
                    && MonetaUTipo.trim().equals(MovimentoRiportato[9]) && MonetaETipo.trim().equals(MovimentoRiportato[12])) {
                ID = IDts[0] + "_" + IDtsOri[1] + "_" + IDtsOri[2] + "_" + IDtsOri[3] + "_" + IDtsOri[4];
                //in alternativa tengo buono l'id automaticamente generato;
            } 
            //Se l'id è uguale a quello vecchio significa che tipo e dataora del movimento sono uguali a quello precedente quindi
            //mi occupo solo di modificare i dati all'interno del movimento (l'id resta uguale)
            if (MovimentoRiportato[0].equals(ID)) {//Qui finiscono solo i movimenti che hanno anche la stessa data
                            MovimentoRiportato[15] = ValoreTransazione;
                            MovimentoRiportato[21] = Note;
                            //MovimentoRiportato[6] = (MonetaU + " -> " + MonetaE).trim();
                            MovimentoRiportato[8] = MonetaU;
                            MovimentoRiportato[9] = MonetaUTipo;
                            MovimentoRiportato[10] = MonetaUQta;
                            MovimentoRiportato[11] = MonetaE;
                            MovimentoRiportato[12] = MonetaETipo;
                            MovimentoRiportato[13] = MonetaEQta;
                            MovimentoRiportato[26] = MonetaUAddress;
                            MovimentoRiportato[28] = MonetaEAddress;
                            if (MovimentoValorizzato) {
                                MovimentoRiportato[32] = "SI";
                            }
                            MovimentoRiportato[40] = Riga40;
             }              
             
            else{
                //1 - Controllo che non vi sia già un movimento con lo stesso ID di quello che voglio generare
                if (MappaCryptoWallet.get(ID) != null) {
                    //System.out.println(ID);
                    JOptionPane.showConfirmDialog(this, "Attenzione!\nEsiste un movimento con lo stesso ID Transsazione\nProvare a modificare l'ora della transazione anche di un solo secondo per risolvere il problema",
                            "Movimento con Stesso ID", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null);
                    return false;
                }//altrimenti chiedo se voglio ricreare il movimento con un nuovo ID
                
                 if (MovimentoRiportato[22].equalsIgnoreCase("AU")) {
                    //System.out.println(ID);
                    JOptionPane.showConfirmDialog(this, "<html>Attenzione!<br>"
                            + "Su questo tipo di movimento è consentito variare solamente Prezzo e Note<br>"
                            + "La modifica non può essere fatta</html>",
                            "Modifica su movimento automatico", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null);
                    return false;
                }//altrimenti chiedo se voglio ricreare il movimento con un nuovo ID               
                String Messaggio = "<html>Attenzione!<br> "
                        + "Il movimento ha subito variazioni di stato per cui verrà ricalcolato l'id ed eliminate le eventuali associazioni già fatte.<br>"
                        + "Si vuole Proseguire?</html>";
                int risposta = JOptionPane.showOptionDialog(this, Messaggio, "Cambio stato movimento", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, "Si");
                //Si=0
                //No=1
                switch (risposta) {
                        case 0 -> {
                            //Cancello il vecchio movimento
                            Funzioni.RimuoviMovimentazioneXID(MovimentoRiportato[0]);
                            String splitID[] = ID.split("_");
                            if (splitID[4].equalsIgnoreCase("RW")) {
                                TipoTransazione = MovimentoRiportato[5];
                            }

                            if (splitID[4].equalsIgnoreCase("CM")) {
                                TipoTransazione = MovimentoRiportato[5];
                            }
                            //Creo il nuovo
                            String RT[];
                            RT = new String[Importazioni.ColonneTabella];
                            RT[0] = ID;
                            RT[1] = Data;
                            RT[2] = MovimentoRiportato[2];
                            RT[3] = Wallet;
                            RT[4] = WalletDettaglio;
                            RT[5] = TipoTransazione;
                            String NomeUscita;
                            String NomeEntrata;
                            
                            //Questa parte serve per mettere il nome della moneta al posto del symbol qualora vi fosse
                            if (MovimentoRiportato[25]!=null&&!MovimentoRiportato[25].isBlank()&&!MonetaU.isBlank())NomeUscita=MovimentoRiportato[25];
                            else NomeUscita=MonetaU;
                            if (MovimentoRiportato[27]!=null&&!MovimentoRiportato[27].isBlank()&&!MonetaE.isBlank())NomeEntrata=MovimentoRiportato[27];
                            else NomeEntrata=MonetaE;
                            
                            
                            RT[6] = (NomeUscita + " -> " + NomeEntrata).trim();
                            RT[8] = MonetaU;
                            RT[9] = MonetaUTipo;
                            RT[10] = MonetaUQta;
                            RT[11] = MonetaE;
                            RT[12] = MonetaETipo;
                            RT[13] = MonetaEQta;
                            RT[14] = MovimentoRiportato[14];
                            RT[15] = ValoreTransazione;
                            RT[21] = Note;
                            RT[22] = "M";
                            RT[23] = MovimentoRiportato[23];
                            RT[24] = MovimentoRiportato[24];
                            RT[25] = MovimentoRiportato[25];
                            RT[26] = MonetaUAddress;
                            RT[27] = MovimentoRiportato[27];
                            RT[28] = MonetaEAddress;
                            RT[29] = MovimentoRiportato[29];
                            RT[30] = MovimentoRiportato[30];
                            RT[31] = MovimentoRiportato[31];
                            if (MovimentoValorizzato) {
                                RT[32] = "SI";
                            }
                            RT[40] = Riga40;
                            Importazioni.RiempiVuotiArray(RT);
                            MappaCryptoWallet.put(RT[0], RT);
                            IDNuovo=RT[0];
                            return true;
                            
                        }
                        case 1 -> {
                            JOptionPane.showConfirmDialog(this, "Operazione Annullata",
                                    "Operazione Annullata", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
                            return false;
                        }
                        case -1 -> {
                            JOptionPane.showConfirmDialog(this, "Operazione Annullata",
                                    "Operazione Annullata", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
                            return false;
                        }

                    }

               // }
                     
        }
        
        }else{
            //se non sto modificando un movimento allora ne creo uno nuovo
                            String RT[];
                            RT = new String[Importazioni.ColonneTabella];
                            RT[0] = ID;
                            RT[1] = Data;
                            RT[2] = "1 di 1";
                            RT[3] = Wallet;
                            RT[4] = WalletDettaglio;
                            RT[5] = TipoTransazione;
                            RT[6] = (MonetaU + " -> " + MonetaE).trim();
                            RT[8] = MonetaU;
                            RT[9] = MonetaUTipo;
                            RT[10] = MonetaUQta;
                            RT[11] = MonetaE;
                            RT[12] = MonetaETipo;
                            RT[13] = MonetaEQta;
                            RT[15] = ValoreTransazione;
                            RT[21] = Note;
                            RT[22] = "M";
                            RT[26] = MonetaUAddress;
                            RT[28] = MonetaEAddress;
                            if (MovimentoValorizzato) {
                                RT[32] = "SI";
                            }
                            RT[40] = Riga40;
                            Importazioni.RiempiVuotiArray(RT);
                            MappaCryptoWallet.put(RT[0], RT); 
                            IDNuovo=RT[0];
        }

        return true;
    }
    
    private boolean EvidenziaProblemi() {                                           
        // TODO add your handling code here:
       // System.out.println(Data_Datachooser.getDate());

       //Se non è compilato il campo prezzo lo valorizzo a zero
       
       if (ValoreTransazione_TextField.getText().isBlank())ValoreTransazione_TextField.setText("0.00");
        //per prima cosa sostituisco le virgole con i punti nei campi numerici
        MonetaUscitaQuantita_TextField.setText(MonetaUscitaQuantita_TextField.getText().replace(",", "."));
        //MonetaUscita_TextField.setText(MonetaUscita_TextField.getText().toUpperCase().replace(";", ""));
        MonetaEntrataQuantita_TextField.setText(MonetaEntrataQuantita_TextField.getText().replace(",", "."));
        //MonetaEntrata_TextField.setText(MonetaEntrata_TextField.getText().toUpperCase().replace(";", ""));
        ValoreTransazione_TextField.setText(ValoreTransazione_TextField.getText().replace(",", "."));
        
        //adesso leggo tutti gli oggetti e li metto in stringhe
        Date Data=this.Data_Datachooser.getDate();
        //String MonetaU=this.MonetaUscita_TextField.getText().trim();
        if (MonetaUscita_ComboBox.getSelectedItem()!=null)MonetaU=this.MonetaUscita_ComboBox.getSelectedItem().toString().replace(";", "").replace(",", "").trim();
        MonetaUQta=this.MonetaUscitaQuantita_TextField.getText().trim();
        MonetaUTipo=this.MonetaUscitaTipo_ComboBox.getSelectedItem().toString();
        MonetaUAddress=this.MonetaUscitaAddress_TextField.getText().trim();
        MonetaEAddress=this.MonetaEntrataAddress_TextField.getText().trim();
        //String MonetaE=this.MonetaEntrata_TextField.getText().trim();
        if (MonetaEntrata_ComboBox.getSelectedItem()!=null)MonetaE=this.MonetaEntrata_ComboBox.getSelectedItem().toString().replace(";", "").replace(",", "").trim();
        MonetaEQta=this.MonetaEntrataQuantita_TextField.getText().trim();
        MonetaETipo=this.MonetaEntrataTipo_ComboBox.getSelectedItem().toString();
        if (MonetaUTipo.equalsIgnoreCase("-----"))MonetaUTipo=null;
        if (MonetaETipo.equalsIgnoreCase("-----"))MonetaETipo=null;
        ValoreTransazione=this.ValoreTransazione_TextField.getText().trim();
        

      if (Wallet_ComboBox.getSelectedItem()!=null)Wallet=this.Wallet_ComboBox.getSelectedItem().toString().replace(";", "").replace(",", "").trim();
      if (WalletDettaglio_ComboBox.getSelectedItem()!=null)WalletDettaglio=this.WalletDettaglio_ComboBox.getSelectedItem().toString().replace(";", "").replace(",", "").trim();

        
        //adesso testo tutti i campi e vedo se manca qualcosa, in quel caso evidenzio i campi mancanti
        boolean nonCompleto=false;
        if (Wallet.equalsIgnoreCase("")){
            nonCompleto=true;
            this.Wallet_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));
        }else {
            this.Wallet_ComboBox.setBackground(Color.white);
        }
        
       if (WalletDettaglio.equalsIgnoreCase("")){
            nonCompleto=true;
            this.WalletDettaglio_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));
        }else {
            this.WalletDettaglio_ComboBox.setBackground(Color.white);
        }
       
        if (/*ValoreTransazione.equalsIgnoreCase("")||*/!Funzioni.isNumeric(ValoreTransazione,false)){
            nonCompleto=true;
            this.ValoreTransazione_TextField.setBackground(Color.getHSBColor(20, 20, 20));
        }else {
            this.ValoreTransazione_TextField.setBackground(Color.white);
        }
        
        if (Data==null){
            nonCompleto=true;
            this.Data_Datachooser.setBackground(Color.orange);
        }else {
            this.Data_Datachooser.setBackground(this.getBackground());
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String DataString=f.format(Data_Datachooser.getDate())+" "+Ora_ComboBox.getSelectedItem().toString()+":"+
            Minuto_ComboBox.getSelectedItem().toString()+":"+Secondo_ComboBox.getSelectedItem().toString();
            DataLong=FunzioniDate.ConvertiDatainLongSecondo(DataString);
        }
        
        
        //in questa prima parte esamino se i blocchi sono interamente compilati o interamente vuoti
        boolean tuttoCompilatoE=false;
        boolean tuttoCompilatoU=false;
        boolean tuttoVuotoE=false;
        boolean tuttoVuotoU=false;
        if (MonetaU.equalsIgnoreCase("")&&MonetaUQta.equalsIgnoreCase("")&&MonetaUTipo==null)
            {
            tuttoVuotoU=true;
            tuttoCompilatoU=false;
            }
        if (!MonetaU.equalsIgnoreCase("")&&!MonetaUQta.equalsIgnoreCase("")&&MonetaUTipo!=null)
            {
            tuttoVuotoU=false;
            tuttoCompilatoU=true;
            }
        
        if (MonetaE.equalsIgnoreCase("")&&MonetaEQta.equalsIgnoreCase("")&&MonetaETipo==null)
            {
            tuttoVuotoE=true;
            tuttoCompilatoE=false;
            }
        if (!MonetaE.equalsIgnoreCase("")&&!MonetaEQta.equalsIgnoreCase("")&&MonetaETipo!=null)
            {
            tuttoVuotoE=false;
            tuttoCompilatoE=true;
            }
      /*  System.out.println(tuttoCompilatoU);
        System.out.println(tuttoCompilatoE);
        System.out.println(tuttoVuotoU);
        System.out.println(tuttoVuotoE);
        System.out.println(MonetaUQta);
        System.out.println(MonetaU);
        System.out.println(MonetaUTipo);
        System.out.println("----");*/
        //se trovo delle compilazioni a metà in uno dei 2 blocchi devo evidenziare il problema
        //se trovo che nessuno dei 2 blocchi è compilato devo evidenziare il problema
        //se invece le 2 situazioni di prima non sono vere vuol dire che va tutto bene

        
        //se trovo delle compilazioni a metà in uno dei 2 blocchi devo evidenziare il problema
        //oppure se trovo che nessuno dei 2 blocchi è compilato devo evidenziare il problema
        //oppure se i campi numerici non sono numerici devo evidenziare il problema
       // System.out.println(CDC_Grafica.Funzioni_isNumeric(MonetaUQta,false));
        if (((tuttoVuotoE==false&&tuttoCompilatoE==false)||(tuttoVuotoU==false&&tuttoCompilatoU==false))||
                (tuttoVuotoE==true&&tuttoVuotoU==true)||
                (!Funzioni.isNumeric(MonetaUQta,true)||!Funzioni.isNumeric(MonetaEQta,true))){
            nonCompleto=true;
            if (MonetaU.equalsIgnoreCase(""))MonetaUscita_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));else MonetaUscita_ComboBox.setBackground(Color.white);
            if (/*MonetaUQta.equalsIgnoreCase("")||*/!Funzioni.isNumeric(MonetaUQta,false))MonetaUscitaQuantita_TextField.setBackground(Color.getHSBColor(20, 20, 20));else MonetaUscitaQuantita_TextField.setBackground(Color.white);
            if (MonetaUTipo==null)MonetaUscitaTipo_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));else MonetaUscitaTipo_ComboBox.setBackground(Color.white);
            if (MonetaE.equalsIgnoreCase(""))MonetaEntrata_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));else MonetaEntrata_ComboBox.setBackground(Color.white);
            if (/*MonetaEQta.equalsIgnoreCase("")||*/!Funzioni.isNumeric(MonetaEQta,false))MonetaEntrataQuantita_TextField.setBackground(Color.getHSBColor(20, 20, 20));else MonetaEntrataQuantita_TextField.setBackground(Color.white);
            if (MonetaETipo==null)MonetaEntrataTipo_ComboBox.setBackground(Color.getHSBColor(20, 20, 20));else MonetaEntrataTipo_ComboBox.setBackground(Color.white);
        } 
        //se invece le 2 situazioni di prima non sono vere vuol dire che va tutto bene
        else{
            MonetaUscita_ComboBox.setBackground(Color.white);
            MonetaUscitaQuantita_TextField.setBackground(Color.white);
            MonetaUscitaTipo_ComboBox.setBackground(Color.white);
            MonetaEntrata_ComboBox.setBackground(Color.white);
            MonetaEntrataQuantita_TextField.setBackground(Color.white);
            MonetaEntrataTipo_ComboBox.setBackground(Color.white);
            
            }
        
               if (!nonCompleto)Bottone_Ok.setEnabled(true);
        else Bottone_Ok.setEnabled(false);
    
    return nonCompleto;
    
    }  
    
    
    
    private String CalcolaID() {
        String ID="";
        if (Data_Datachooser.getDate()!=null)
            {
            SimpleDateFormat f = new SimpleDateFormat("yyyyMMdd");
            String Data=f.format(Data_Datachooser.getDate());
            ID=ID+Data+Ora_ComboBox.getSelectedItem().toString()+
                    Minuto_ComboBox.getSelectedItem().toString()+
                    Secondo_ComboBox.getSelectedItem().toString()+
                    "_";         
            }
        if (Wallet_ComboBox.getSelectedItem()!=null)
            ID=ID+Wallet_ComboBox.getSelectedItem().toString().replace(";", "").replace(" ", "").replace(".", "").replace(",", "").replace("_", "").trim()+".";
        
        if (WalletDettaglio_ComboBox.getSelectedItem()!=null)
            ID=ID+WalletDettaglio_ComboBox.getSelectedItem().toString().replace(";", "").replace(" ", "").replace(".", "").replace(",", "").replace("_", "").trim()+"_1_1_";
        else
            ID=ID+"Principale"+"_1_1_";//Se non esiste il Wallet dettaglio lo chiamo Principale
        //Adesso devo individuare la tipologia di movimento quindi possono essere le seguenti
         //TI=Trasferimento Interno
         //DC=Deposito Criptoattività
         //PC=Prelievo Criptoattività
         //DF=Deposito Fiat
         //PF=Prelievo Fiat
         //AC=Acquisto Criptoattività (con FIAT)
         //VC=Vendita Criptoattività (per FIAT)
         //SC=Scambio Criptoattività
         //RW=Staking/caschback/airdrop etc....
         //CM=Commissioni/Fees
        ID=ID+Importazioni.RitornaTipologiaTransazione(MonetaUTipo,MonetaETipo,0);
       // System.out.println(ID);
      // String IDScritto=this.ID_TextField.getText();
       //se ho recuperato l'id dalla transazione tengo quello
     //  if (IDScritto.equalsIgnoreCase(""))
        return ID;
      // else return IDScritto;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ModificaMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ModificaMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ModificaMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ModificaMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ModificaMovimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Annulla;
    private javax.swing.JButton Bottone_ModificaPrezzo;
    private javax.swing.JButton Bottone_Ok;
    private com.toedter.calendar.JDateChooser Data_Datachooser;
    private javax.swing.JLabel Data_Label;
    private javax.swing.JLabel Freccia1_Label;
    private javax.swing.JLabel Freccia2_Label;
    private javax.swing.JLabel Freccia3_Label;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JComboBox<String> Minuto_ComboBox;
    private javax.swing.JLabel Minuto_Label;
    private javax.swing.JLabel MonetaEntrataAddress_Label;
    private javax.swing.JTextField MonetaEntrataAddress_TextField;
    private javax.swing.JLabel MonetaEntrataQuantita_Label;
    private javax.swing.JTextField MonetaEntrataQuantita_TextField;
    private javax.swing.JComboBox<String> MonetaEntrataTipo_ComboBox;
    private javax.swing.JLabel MonetaEntrataTipo_Label;
    private javax.swing.JComboBox<String> MonetaEntrata_ComboBox;
    private javax.swing.JLabel MonetaEntrata_Label;
    private javax.swing.JLabel MonetaUscitaAddress_Label;
    private javax.swing.JTextField MonetaUscitaAddress_TextField;
    private javax.swing.JLabel MonetaUscitaQuantita_Label;
    private javax.swing.JTextField MonetaUscitaQuantita_TextField;
    private javax.swing.JComboBox<String> MonetaUscitaTipo_ComboBox;
    private javax.swing.JLabel MonetaUscitaTipo_Label;
    private javax.swing.JComboBox<String> MonetaUscita_ComboBox;
    private javax.swing.JLabel MonetaUscita_Label;
    private javax.swing.JLabel Note_Label;
    private javax.swing.JScrollPane Note_ScrollPane;
    private javax.swing.JTextArea Note_TextArea;
    private javax.swing.JComboBox<String> Ora_ComboBox;
    private javax.swing.JLabel Ora_Label;
    private javax.swing.JLabel P_LabelFonte;
    private javax.swing.JLabel P_LabelMoneta;
    private javax.swing.JLabel P_LabelPU;
    private javax.swing.JLabel P_LabelTimeFonte;
    private javax.swing.JTextField P_TextFonte;
    private javax.swing.JTextField P_TextMoneta;
    private javax.swing.JTextField P_TextPU;
    private javax.swing.JTextField P_TextTimeFonte;
    private javax.swing.JComboBox<String> Secondo_ComboBox;
    private javax.swing.JLabel Secondo_Label;
    private javax.swing.JLabel ValoreTransazione_Label;
    private javax.swing.JTextField ValoreTransazione_TextField;
    private javax.swing.JComboBox<String> WalletDettaglio_ComboBox;
    private javax.swing.JLabel WalletDettaglio_Label;
    private javax.swing.JComboBox<String> Wallet_ComboBox;
    private javax.swing.JLabel Wallet_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
