package com.giacenzecrypto.giacenze_crypto;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * Pannello di gestione dei documenti di origine: elenca i file da cui i movimenti sono stati importati,
 * con quanti movimenti vi sono agganciati oggi, su quali wallet e in che periodo, e permette di aprirne
 * una copia, di esportarli decompressi e di eliminare quelli a cui non punta più nessun movimento.
 *
 * <p>La logica operativa sta in {@link Principale_DocumentiFonte}: qui restano solo la costruzione della
 * finestra, il popolamento della tabella e l'abilitazione dei pulsanti.
 */
public class GUI_DocumentiFonte extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Indice della colonna "Movimenti", quella che decide se un documento sia eliminabile.
     * <p>La costante è quella di {@link Principale_DocumentiFonte}, che è anche chi riempie le righe:
     * tenerne due copie significherebbe poterle disallineare.
     */
    private static final int COL_MOVIMENTI = Principale_DocumentiFonte.COLONNA_MOVIMENTI;

    /**
     * Apre il pannello.
     * @param Proprietario finestra rispetto a cui centrarsi
     */
    public static void Mostra(Window Proprietario) {
        GUI_DocumentiFonte g = new GUI_DocumentiFonte(Proprietario);
        g.setLocationRelativeTo(Proprietario);
        g.setVisible(true);
    }

    /**
     * Crea la finestra.
     * @param Proprietario finestra parent
     */
    private GUI_DocumentiFonte(Window Proprietario) {
        super(Proprietario, ModalityType.APPLICATION_MODAL);
        initComponents();

        Tabelle.Tabelle_ApplicaHeaderBoldCentrato(Tabella);

        //L'abilitazione dei pulsanti segue la selezione. Il listener resta scritto a mano: il GUI Builder
        //non modella gli eventi del modello di selezione di una JTable.
        Tabella.getSelectionModel().addListSelectionListener(e -> AggiornaStatoPulsanti());

        Ricarica();

        //Prima si impacchetta sul contenuto, poi si allarga: partendo da una dimensione fissa la riga in
        //fondo veniva tagliata, perché fra etichetta di riepilogo e cinque pulsanti con icona serve più
        //spazio di quanto se ne indovini a priori. Il minimo è quello che il layout dichiara di volere,
        //così la finestra non è mai rimpicciolibile fino a nascondere i pulsanti.
        pack();
        setMinimumSize(getSize());
        setSize(Math.max(getWidth(), 1200), Math.max(getHeight(), 600));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane_Tabella = new javax.swing.JScrollPane();
        Tabella = new javax.swing.JTable();
        Label_Riepilogo = new javax.swing.JLabel();
        Bottone_Apri = new javax.swing.JButton();
        Bottone_Esporta = new javax.swing.JButton();
        Bottone_Elimina = new javax.swing.JButton();
        Bottone_Aggiorna = new javax.swing.JButton();
        Bottone_Chiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Documenti di origine dei movimenti");

        Tabella.setAutoCreateRowSorter(true);
        Tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Documento", "Tipo", "Origine", "Importato il", "Dimensione", "Su disco", "Movimenti", "Wallet / Exchange", "Periodo dei movimenti"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane_Tabella.setViewportView(Tabella);

        Bottone_Apri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Documento.png"))); // NOI18N
        Bottone_Apri.setText("Apri una copia");
        Bottone_Apri.setToolTipText("Il documento è conservato compresso: viene scompattata una copia nella cartella Temporanei e aperta quella, così l'originale non è modificabile");
        Bottone_Apri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_ApriActionPerformed(evt);
            }
        });

        Bottone_Esporta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Esporta.setText("Esporta selezionati...");
        Bottone_Esporta.setToolTipText("Scrive i documenti selezionati, decompressi, in una cartella a scelta");
        Bottone_Esporta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_EsportaActionPerformed(evt);
            }
        });

        Bottone_Elimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Cestino.png"))); // NOI18N
        Bottone_Elimina.setText("Elimina");
        Bottone_Elimina.setToolTipText("Possibile solo sui documenti a cui non è agganciato più nessun movimento");
        Bottone_Elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_EliminaActionPerformed(evt);
            }
        });

        Bottone_Aggiorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Aggiorna.png"))); // NOI18N
        Bottone_Aggiorna.setText("Aggiorna");
        Bottone_Aggiorna.setToolTipText("Rilegge il registro e ricalcola i movimenti agganciati");
        Bottone_Aggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AggiornaActionPerformed(evt);
            }
        });

        Bottone_Chiudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Annulla.png"))); // NOI18N
        Bottone_Chiudi.setText("Chiudi");
        Bottone_Chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_ChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_Tabella, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Riepilogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bottone_Apri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Esporta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Elimina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bottone_Aggiorna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Chiudi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane_Tabella, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Riepilogo)
                    .addComponent(Bottone_Apri)
                    .addComponent(Bottone_Esporta)
                    .addComponent(Bottone_Elimina)
                    .addComponent(Bottone_Aggiorna)
                    .addComponent(Bottone_Chiudi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone_ApriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_ApriActionPerformed
        List<Integer> ids = IdSelezionati();
        if (ids.size() == 1) {
            Principale_DocumentiFonte.ApriDocumento(ids.get(0), this);
        }
    }//GEN-LAST:event_Bottone_ApriActionPerformed

    private void Bottone_EsportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_EsportaActionPerformed
        if (Principale_DocumentiFonte.EsportaDocumenti(IdSelezionati(), this)) {
            Ricarica();
        }
    }//GEN-LAST:event_Bottone_EsportaActionPerformed

    private void Bottone_EliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_EliminaActionPerformed
        if (Principale_DocumentiFonte.EliminaDocumenti(IdSelezionati(), this)) {
            Ricarica();
        }
    }//GEN-LAST:event_Bottone_EliminaActionPerformed

    private void Bottone_AggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AggiornaActionPerformed
        Ricarica();
    }//GEN-LAST:event_Bottone_AggiornaActionPerformed

    private void Bottone_ChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_ChiudiActionPerformed
        dispose();
    }//GEN-LAST:event_Bottone_ChiudiActionPerformed

    /** @return il modello della tabella, creato nel form */
    private DefaultTableModel Modello() {
        return (DefaultTableModel) Tabella.getModel();
    }

    /** Ricostruisce la tabella dal registro e dai movimenti attualmente in mappa. */
    private void Ricarica() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            Modello().setRowCount(0);
            List<Object[]> righe = Principale_DocumentiFonte.RigheDiRiepilogo();
            for (Object[] r : righe) {
                Modello().addRow(r);
            }
            Label_Riepilogo.setText(Principale_DocumentiFonte.TestoRiepilogo(righe));
            AdattaLarghezzaColonne();
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
        AggiornaStatoPulsanti();
    }

    /**
     * Porta ogni colonna alla larghezza del suo contenuto più lungo.
     * <p>La tabella è a {@code AUTO_RESIZE_OFF} perché l'elenco dei wallet e il nome dei documenti possono
     * essere lunghi: meglio uno scorrimento orizzontale che dieci colonne tutte troncate.
     */
    private void AdattaLarghezzaColonne() {
        for (int c = 0; c < Tabella.getColumnCount(); c++) {
            int larghezza = Tabella.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(Tabella, Modello().getColumnName(c), false, false, 0, c)
                    .getPreferredSize().width;
            for (int r = 0; r < Tabella.getRowCount(); r++) {
                larghezza = Math.max(larghezza, Tabella.prepareRenderer(Tabella.getCellRenderer(r, c), r, c)
                        .getPreferredSize().width);
            }
            Tabella.getColumnModel().getColumn(c).setPreferredWidth(Math.min(larghezza + 20, 400));
        }
    }

    /** @return gli id dei documenti selezionati, nell'ordine in cui compaiono nella tabella */
    private List<Integer> IdSelezionati() {
        List<Integer> ids = new ArrayList<>();
        for (int riga : Tabella.getSelectedRows()) {
            ids.add((Integer) Modello().getValueAt(Tabella.convertRowIndexToModel(riga), 0));
        }
        return ids;
    }

    /** @return {@code true} se ogni documento selezionato non ha più movimenti agganciati */
    private boolean TuttiSenzaMovimenti() {
        for (int riga : Tabella.getSelectedRows()) {
            if ((Integer) Modello().getValueAt(Tabella.convertRowIndexToModel(riga), COL_MOVIMENTI) > 0) {
                return false;
            }
        }
        return true;
    }

    private void AggiornaStatoPulsanti() {
        int selezionati = Tabella.getSelectedRowCount();
        //"Apri" lavora sul singolo: aprire dieci file insieme non è quello che si intende chiedendolo
        Bottone_Apri.setEnabled(selezionati == 1);
        Bottone_Esporta.setEnabled(selezionati > 0);
        Bottone_Elimina.setEnabled(selezionati > 0 && TuttiSenzaMovimenti());
        Bottone_Elimina.setToolTipText(selezionati > 0 && !TuttiSenzaMovimenti()
                ? "La selezione contiene documenti a cui sono ancora agganciati dei movimenti"
                : "Possibile solo sui documenti a cui non è agganciato più nessun movimento");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Aggiorna;
    private javax.swing.JButton Bottone_Apri;
    private javax.swing.JButton Bottone_Chiudi;
    private javax.swing.JButton Bottone_Elimina;
    private javax.swing.JButton Bottone_Esporta;
    private javax.swing.JLabel Label_Riepilogo;
    private javax.swing.JScrollPane ScrollPane_Tabella;
    private javax.swing.JTable Tabella;
    // End of variables declaration//GEN-END:variables
}
