package com.giacenzecrypto.giacenze_crypto;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Window;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * Parte grafica di "Backup / Ripristino": elenca gli archivi presenti in {@code ArchivioBackup/}, ne
 * mostra il dettaglio e offre le cinque operazioni (esegui, ripristina, esporta, importa, elimina).
 *
 * <p>Come {@link GUI_DocumentiFonte_Pannello} è un {@link javax.swing.JPanel} e non una finestra, così
 * da poter vivere dentro il sotto-tab di <i>Opzioni</i> senza far crescere il {@code .form} di
 * {@code Principale}, che è già oltre il mezzo megabyte. La logica operativa sta in
 * {@link Principale_Backup}, il motore in {@link Backup_Restore}.
 *
 * <p>Due cose che dipendono dall'essere un pannello:
 * <ul>
 *   <li>la finestra a cui agganciare i dialoghi si risolve <b>a ogni chiamata</b> con
 *       {@link #Proprietario()} : quando il pannello viene costruito un antenato ancora non c'è;</li>
 *   <li>il ripristino non ricarica niente da sé. Rileggere {@code MappaCryptoWallet} e rifare i calcoli
 *       richiede metodi privati di {@code Principale}, quindi il pannello si limita a <b>notificare</b>
 *       l'esito tramite {@link #ImpostaAzionePostRipristino(java.util.function.Consumer)}, che
 *       {@code Principale} valorizza quando monta il pannello. È lo stesso schema del pulsante
 *       <i>Chiudi</i> di {@code GUI_DocumentiFonte_Pannello}, e serve a tenere il refresh dove sta
 *       tutto l'altro refresh.</li>
 * </ul>
 */
public class GUI_Backup_Pannello extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /** I manifesti nell'ordine in cui compaiono nella tabella superiore. */
    private List<Backup_Restore.Manifest> Manifesti = new ArrayList<>();

    /** Cosa far fare a {@code Principale} dopo un ripristino riuscito; {@code null} finché non impostata. */
    private Consumer<Backup_Restore.EsitoRipristino> AzionePostRipristino = null;

    /** Crea il pannello e lo riempie. */
    public GUI_Backup_Pannello() {
        initComponents();

        //Come in GUI_DocumentiFonte_Pannello: anche questo pannello nasce pigramente al primo
        //componentShown del tab, quando la visita alle icone della finestra è già passata.
        Icone.AdattaIconeAlTema(this);

        Tabelle.Tabelle_ApplicaHeaderBoldCentrato(Tabella_Elenco);
        Tabelle.Tabelle_ApplicaHeaderBoldCentrato(Tabella_Dettaglio);
        Tabelle.ColoraTabellaSemplice(Tabella_Elenco);
        Tabelle.ColoraTabellaSemplice(Tabella_Dettaglio);

        //L'abilitazione dei pulsanti e il dettaglio seguono la selezione. Il listener resta scritto a
        //mano: il GUI Builder non modella gli eventi del modello di selezione di una JTable.
        Tabella_Elenco.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                MostraDettaglio();
                AggiornaStatoPulsanti();
            }
        });

        Ricarica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane_Elenco = new javax.swing.JScrollPane();
        Tabella_Elenco = new javax.swing.JTable();
        Label_Dettaglio = new javax.swing.JLabel();
        ScrollPane_Dettaglio = new javax.swing.JScrollPane();
        Tabella_Dettaglio = new javax.swing.JTable();
        Label_Riepilogo = new javax.swing.JLabel();
        Bottone_Esegui = new javax.swing.JButton();
        Bottone_Ripristina = new javax.swing.JButton();
        Bottone_Esporta = new javax.swing.JButton();
        Bottone_Importa = new javax.swing.JButton();
        Bottone_Elimina = new javax.swing.JButton();
        Bottone_Aggiorna = new javax.swing.JButton();

        Tabella_Elenco.setAutoCreateRowSorter(true);
        Tabella_Elenco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data del backup", "Movimenti", "Primo movimento", "Ultimo movimento", "Prezzi", "Documenti", "Dimensione", "Versione", "Origine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane_Elenco.setViewportView(Tabella_Elenco);

        Label_Dettaglio.setText("Dettaglio del backup selezionato");

        Tabella_Dettaglio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voce", "Valore"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane_Dettaglio.setViewportView(Tabella_Dettaglio);

        Bottone_Esegui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Esegui.setText("Esegui Backup");
        Bottone_Esegui.setToolTipText("Crea un nuovo archivio completo nella cartella ArchivioBackup");
        Bottone_Esegui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_EseguiActionPerformed(evt);
            }
        });

        Bottone_Ripristina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_FrecceContrapposte.png"))); // NOI18N
        Bottone_Ripristina.setText("Ripristina Backup");
        Bottone_Ripristina.setToolTipText("Sostituisce i dati attuali con quelli del backup selezionato, previo backup di sicurezza");
        Bottone_Ripristina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_RipristinaActionPerformed(evt);
            }
        });

        Bottone_Esporta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Upload.png"))); // NOI18N
        Bottone_Esporta.setText("Esporta Backup");
        Bottone_Esporta.setToolTipText("Copia l'archivio selezionato in una cartella a scelta");
        Bottone_Esporta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_EsportaActionPerformed(evt);
            }
        });

        Bottone_Importa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_FrecciaSotto.png"))); // NOI18N
        Bottone_Importa.setText("Importa Backup");
        Bottone_Importa.setToolTipText("Aggiunge all'elenco un archivio conservato altrove");
        Bottone_Importa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_ImportaActionPerformed(evt);
            }
        });

        Bottone_Elimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Cestino.png"))); // NOI18N
        Bottone_Elimina.setText("Elimina");
        Bottone_Elimina.setToolTipText("Gli archivi non scadono mai: questo è l'unico modo per liberare spazio");
        Bottone_Elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_EliminaActionPerformed(evt);
            }
        });

        Bottone_Aggiorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Aggiorna.png"))); // NOI18N
        Bottone_Aggiorna.setText("Aggiorna");
        Bottone_Aggiorna.setToolTipText("Rilegge la cartella degli archivi");
        Bottone_Aggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AggiornaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_Elenco, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
                    .addComponent(ScrollPane_Dettaglio, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
                    .addComponent(Label_Dettaglio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Riepilogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bottone_Esegui, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Ripristina, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Esporta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Importa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bottone_Aggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane_Elenco, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Dettaglio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Dettaglio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Riepilogo)
                    .addComponent(Bottone_Esegui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Ripristina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Esporta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Importa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone_Aggiorna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone_EseguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_EseguiActionPerformed
        if (Principale_Backup.EseguiBackup(Proprietario()) != null) {
            Ricarica();
        }
    }//GEN-LAST:event_Bottone_EseguiActionPerformed

    private void Bottone_RipristinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_RipristinaActionPerformed
        Backup_Restore.Manifest m = Selezionato();
        if (m == null || m.Archivio == null) {
            return;
        }
        Backup_Restore.EsitoRipristino esito = Principale_Backup.RipristinaBackup(m.Archivio, Proprietario());
        if (esito == null) {
            return;
        }
        //Il backup di sicurezza creato prima del ripristino è un archivio nuovo: l'elenco va riletto
        //comunque, anche se il ripristino è poi fallito
        Ricarica();
        if (AzionePostRipristino != null) {
            AzionePostRipristino.accept(esito);
        } else {
            //Montato fuori da Principale non c'è nessuno che possa ricaricare: meglio dirlo che lasciare
            //l'applicazione con i dati vecchi in memoria e quelli nuovi su disco
            Messaggi.WarningMessage("Ripristino",
                    "I dati sono stati ripristinati ma l'applicazione non li ha ancora ricaricati.",
                    "Chiudi e riapri Giacenze Crypto per lavorare sui dati ripristinati.", Proprietario());
        }
    }//GEN-LAST:event_Bottone_RipristinaActionPerformed

    private void Bottone_EsportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_EsportaActionPerformed
        Backup_Restore.Manifest m = Selezionato();
        if (m != null && m.Archivio != null) {
            Principale_Backup.EsportaBackup(m.Archivio, Proprietario());
        }
    }//GEN-LAST:event_Bottone_EsportaActionPerformed

    private void Bottone_ImportaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_ImportaActionPerformed
        File importato = Principale_Backup.ImportaBackup(Proprietario());
        Ricarica();
        //ImportaBackup ritorna un file solo se l'utente ha chiesto di ripristinarlo subito: in quel caso
        //si seleziona la riga e si passa dalla stessa conferma del pulsante, senza scorciatoie
        if (importato != null) {
            SelezionaArchivio(importato);
            Bottone_RipristinaActionPerformed(evt);
        }
    }//GEN-LAST:event_Bottone_ImportaActionPerformed

    private void Bottone_EliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_EliminaActionPerformed
        List<File> archivi = new ArrayList<>();
        for (int riga : Tabella_Elenco.getSelectedRows()) {
            Backup_Restore.Manifest m = Manifesti.get(Tabella_Elenco.convertRowIndexToModel(riga));
            if (m.Archivio != null) {
                archivi.add(m.Archivio);
            }
        }
        if (Principale_Backup.EliminaBackup(archivi, Proprietario())) {
            Ricarica();
        }
    }//GEN-LAST:event_Bottone_EliminaActionPerformed

    private void Bottone_AggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AggiornaActionPerformed
        Ricarica();
    }//GEN-LAST:event_Bottone_AggiornaActionPerformed

    /**
     * Dice al pannello cosa far eseguire dopo un ripristino riuscito.
     *
     * <p>Da valorizzare da {@code Principale} : ricaricare i movimenti, invalidare lo stato del motore
     * incrementale e rifare i calcoli richiede metodi che stanno lì e che non sono raggiungibili da qui.
     *
     * @param Azione riceve l'esito del ripristino
     */
    public void ImpostaAzionePostRipristino(Consumer<Backup_Restore.EsitoRipristino> Azione) {
        AzionePostRipristino = Azione;
    }

    /** Rilegge la cartella degli archivi e ricostruisce le due tabelle. */
    public final void Ricarica() {
        Component c = Proprietario() != null ? Proprietario() : this;
        c.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            Manifesti = Backup_Restore.Elenco();
            ModelloElenco().setRowCount(0);
            for (Object[] r : Principale_Backup.RigheElenco(Manifesti)) {
                ModelloElenco().addRow(r);
            }
            Label_Riepilogo.setText(TestoRiepilogo());
            AdattaLarghezzaColonne(Tabella_Elenco);
        } finally {
            c.setCursor(Cursor.getDefaultCursor());
        }
        MostraDettaglio();
        AggiornaStatoPulsanti();
    }

    /**
     * @return la riga di riepilogo in fondo al pannello
     *
     * <p>Volutamente <b>corta</b>: sta nella stessa riga dei sei pulsanti, e in un
     * {@code GroupLayout} una {@code JLabel} non si restringe sotto la propria larghezza preferita —
     * un testo lungo spingerebbe l'ultimo pulsante fuori dal pannello. Il resto (la ritenzione eterna,
     * il fatto che si cancelli solo a mano) sta nel tooltip di <i>Elimina</i>, dove serve davvero.
     */
    private String TestoRiepilogo() {
        long byteTotali = 0;
        for (Backup_Restore.Manifest m : Manifesti) {
            byteTotali += m.DimensioneCompressa;
        }
        if (Manifesti.isEmpty()) {
            return "Nessun backup presente";
        }
        return Manifesti.size() + (Manifesti.size() == 1 ? " backup, " : " backup, ")
                + Backup_Restore.DimensioneLeggibile(byteTotali);
    }

    /** Riempie la tabella inferiore con il dettaglio della riga selezionata. */
    private void MostraDettaglio() {
        ModelloDettaglio().setRowCount(0);
        for (Object[] r : Principale_Backup.RigheDettaglio(Selezionato())) {
            ModelloDettaglio().addRow(r);
        }
        AdattaLarghezzaColonne(Tabella_Dettaglio);
    }

    /** @return il manifest della riga selezionata, {@code null} se la selezione non è di una sola riga */
    private Backup_Restore.Manifest Selezionato() {
        if (Tabella_Elenco.getSelectedRowCount() != 1) {
            return null;
        }
        int riga = Tabella_Elenco.convertRowIndexToModel(Tabella_Elenco.getSelectedRow());
        return riga >= 0 && riga < Manifesti.size() ? Manifesti.get(riga) : null;
    }

    /** Seleziona la riga che corrisponde a un archivio, se presente. */
    private void SelezionaArchivio(File Archivio) {
        for (int i = 0; i < Manifesti.size(); i++) {
            if (Archivio.equals(Manifesti.get(i).Archivio)) {
                int vista = Tabella_Elenco.convertRowIndexToView(i);
                if (vista >= 0) {
                    Tabella_Elenco.setRowSelectionInterval(vista, vista);
                }
                return;
            }
        }
    }

    private void AggiornaStatoPulsanti() {
        int selezionate = Tabella_Elenco.getSelectedRowCount();
        //Ripristino ed esportazione lavorano su un archivio solo: non esiste un ripristino "di due backup"
        Bottone_Ripristina.setEnabled(selezionate == 1);
        Bottone_Esporta.setEnabled(selezionate == 1);
        Bottone_Elimina.setEnabled(selezionate > 0);
    }

    /**
     * La finestra a cui agganciare dialoghi e messaggi.
     * <p>Va risolta a ogni chiamata e non memorizzata nel costruttore : montato dentro un tab, il pannello
     * viene costruito quando un antenato ancora non c'è.
     */
    private Window Proprietario() {
        return SwingUtilities.getWindowAncestor(this);
    }

    private DefaultTableModel ModelloElenco() {
        return (DefaultTableModel) Tabella_Elenco.getModel();
    }

    private DefaultTableModel ModelloDettaglio() {
        return (DefaultTableModel) Tabella_Dettaglio.getModel();
    }

    /** Porta ogni colonna alla larghezza del suo contenuto più lungo, con un tetto. */
    private void AdattaLarghezzaColonne(javax.swing.JTable t) {
        DefaultTableModel modello = (DefaultTableModel) t.getModel();
        for (int c = 0; c < t.getColumnCount(); c++) {
            int larghezza = t.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(t, modello.getColumnName(c), false, false, 0, c)
                    .getPreferredSize().width;
            for (int r = 0; r < t.getRowCount(); r++) {
                larghezza = Math.max(larghezza,
                        t.prepareRenderer(t.getCellRenderer(r, c), r, c).getPreferredSize().width);
            }
            t.getColumnModel().getColumn(c).setPreferredWidth(Math.min(larghezza + 20, 500));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Aggiorna;
    private javax.swing.JButton Bottone_Elimina;
    private javax.swing.JButton Bottone_Esegui;
    private javax.swing.JButton Bottone_Esporta;
    private javax.swing.JButton Bottone_Importa;
    private javax.swing.JButton Bottone_Ripristina;
    private javax.swing.JLabel Label_Dettaglio;
    private javax.swing.JLabel Label_Riepilogo;
    private javax.swing.JScrollPane ScrollPane_Dettaglio;
    private javax.swing.JScrollPane ScrollPane_Elenco;
    private javax.swing.JTable Tabella_Dettaglio;
    private javax.swing.JTable Tabella_Elenco;
    // End of variables declaration//GEN-END:variables
}
