/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.giacenzecrypto.giacenze_crypto;

import java.util.List;

import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COLONNE;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_CHIAVE_DEFAULT;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_DATA_FINE;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_DATA_INIZIO;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_FONTE;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_IDENT;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_NOME;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_NOTE;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_ORIGINE;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_PROGRESSIVO;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.COL_STATO;
import static com.giacenzecrypto.giacenze_crypto.Principale_PeriodiExchange.ORIGINE_UTENTE;

/**
 * Dialogo dedicato per aggiungere / modificare <b>un periodo fiscale di un exchange</b>
 * ({@code EXCHANGE_PERIODO}). Sostituisce l'editing in cella di {@link GUI_PeriodiExchange} : date da
 * calendario, non da digitare, e Stato estero scelto da elenco ({@link StatiEsteri}). La riga
 * prodotta ({@link #risultato}, {@link Principale_PeriodiExchange#COLONNE} colonne) ha sempre
 * {@code Origine = UTENTE} — la {@code ChiaveDefault} eventuale viene mantenuta, così una riga
 * ex-predefinita modificata resta riconoscibile come "Modificato".
 */
public class GUI_ModificaPeriodoExchange extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private final String chiaveDefault;

    public boolean confermato = false;
    public String[] risultato;

    public GUI_ModificaPeriodoExchange(java.awt.Window owner, String[] rigaEsistente, int progressivoProposto) {
        super(owner, ModalityType.APPLICATION_MODAL);
        try {
            setIconImage(new javax.swing.ImageIcon(VarStatiche.getPathRisorse() + "logo.png").getImage());
        } catch (RuntimeException ignore) {
        }
        initComponents();

        boolean nuovo = rigaEsistente == null;
        setTitle(nuovo ? "Nuovo periodo fiscale" : "Modifica periodo fiscale");

        RwDialoghi.configura(Data_Inizio);
        RwDialoghi.configura(Data_Fine);

        Campo_Prog.setText(nuovo ? String.valueOf(progressivoProposto) : val(rigaEsistente, COL_PROGRESSIVO));
        RwDialoghi.impostaData(Data_Inizio, nuovo ? "" : val(rigaEsistente, COL_DATA_INIZIO));
        RwDialoghi.impostaData(Data_Fine, nuovo ? "" : val(rigaEsistente, COL_DATA_FINE));
        Campo_Nome.setText(nuovo ? "" : val(rigaEsistente, COL_NOME));

        String statoCorrente = nuovo ? "" : val(rigaEsistente, COL_STATO);
        for (String voce : StatiEsteri.etichetteCombo(statoCorrente)) {
            Combo_Stato.addItem(voce);
        }
        Combo_Stato.setSelectedItem(StatiEsteri.etichetta(statoCorrente));

        Campo_Ident.setText(nuovo ? "" : val(rigaEsistente, COL_IDENT));
        Campo_Note.setText(nuovo ? "" : val(rigaEsistente, COL_NOTE));
        Campo_Fonte.setText(nuovo ? "" : val(rigaEsistente, COL_FONTE));
        this.chiaveDefault = nuovo ? "" : val(rigaEsistente, COL_CHIAVE_DEFAULT);

        getRootPane().setDefaultButton(Bottone_Ok);
        pack();
        setLocationRelativeTo(owner);
    }

    private static String val(String[] r, int i) {
        return r != null && i >= 0 && i < r.length && r[i] != null ? r[i] : "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Pannello_Campi = new javax.swing.JPanel();
        Label_Prog = new javax.swing.JLabel();
        Campo_Prog = new javax.swing.JTextField();
        Label_DataInizio = new javax.swing.JLabel();
        Data_Inizio = new com.toedter.calendar.JDateChooser();
        Label_DataFine = new javax.swing.JLabel();
        Data_Fine = new com.toedter.calendar.JDateChooser();
        Label_Nome = new javax.swing.JLabel();
        Campo_Nome = new javax.swing.JTextField();
        Label_Stato = new javax.swing.JLabel();
        Combo_Stato = new javax.swing.JComboBox();
        Label_Ident = new javax.swing.JLabel();
        Campo_Ident = new javax.swing.JTextField();
        Label_Note = new javax.swing.JLabel();
        Scroll_Note = new javax.swing.JScrollPane();
        Campo_Note = new javax.swing.JTextArea();
        Label_Fonte = new javax.swing.JLabel();
        Scroll_Fonte = new javax.swing.JScrollPane();
        Campo_Fonte = new javax.swing.JTextArea();
        Pannello_Pulsanti = new javax.swing.JPanel();
        Bottone_Ok = new javax.swing.JButton();
        Bottone_Annulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifica periodo fiscale");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        Pannello_Campi.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 8, 12));
        Pannello_Campi.setLayout(new java.awt.GridBagLayout());

        Label_Prog.setText("Progressivo :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_Prog, gridBagConstraints);

        Campo_Prog.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Campo_Prog, gridBagConstraints);

        Label_DataInizio.setText("Data inizio (vuota = da sempre) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_DataInizio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Data_Inizio, gridBagConstraints);

        Label_DataFine.setText("Data fine (vuota = ancora in corso) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_DataFine, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Data_Fine, gridBagConstraints);

        Label_Nome.setText("Nome entita' legale :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_Nome, gridBagConstraints);

        Campo_Nome.setColumns(24);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Campo_Nome, gridBagConstraints);

        Label_Stato.setText("Stato estero (Tabella 10 Redditi PF) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_Stato, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Combo_Stato, gridBagConstraints);

        Label_Ident.setText("Identificativo fiscale (max 15) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_Ident, gridBagConstraints);

        Campo_Ident.setColumns(18);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Campo_Ident, gridBagConstraints);

        Label_Note.setText("Note :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 10);
        Pannello_Campi.add(Label_Note, gridBagConstraints);

        Campo_Note.setColumns(30);
        Campo_Note.setLineWrap(true);
        Campo_Note.setRows(4);
        Campo_Note.setWrapStyleWord(true);
        Scroll_Note.setViewportView(Campo_Note);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Pannello_Campi.add(Scroll_Note, gridBagConstraints);

        Label_Fonte.setText("Fonte :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        Pannello_Campi.add(Label_Fonte, gridBagConstraints);

        Campo_Fonte.setColumns(30);
        Campo_Fonte.setLineWrap(true);
        Campo_Fonte.setRows(3);
        Campo_Fonte.setWrapStyleWord(true);
        Scroll_Fonte.setViewportView(Campo_Fonte);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        Pannello_Campi.add(Scroll_Fonte, gridBagConstraints);

        getContentPane().add(Pannello_Campi, java.awt.BorderLayout.CENTER);

        Pannello_Pulsanti.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        Pannello_Pulsanti.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        Bottone_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Salva.png"))); // NOI18N
        Bottone_Ok.setText("OK");
        Bottone_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_OkActionPerformed(evt);
            }
        });
        Pannello_Pulsanti.add(Bottone_Ok);

        Bottone_Annulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/24_Annulla.png"))); // NOI18N
        Bottone_Annulla.setText("Annulla");
        Bottone_Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone_AnnullaActionPerformed(evt);
            }
        });
        Pannello_Pulsanti.add(Bottone_Annulla);

        getContentPane().add(Pannello_Pulsanti, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_OkActionPerformed
        String[] r = new String[COLONNE];
        java.util.Arrays.fill(r, "");
        r[COL_PROGRESSIVO] = Campo_Prog.getText().trim();
        r[COL_DATA_INIZIO] = RwDialoghi.leggiData(Data_Inizio);
        r[COL_DATA_FINE] = RwDialoghi.leggiData(Data_Fine);
        r[COL_NOME] = Campo_Nome.getText().trim();
        r[COL_STATO] = StatiEsteri.codiceDaEtichetta(String.valueOf(Combo_Stato.getSelectedItem()));
        r[COL_IDENT] = Campo_Ident.getText().trim();
        r[COL_NOTE] = Campo_Note.getText().trim();
        r[COL_FONTE] = Campo_Fonte.getText().trim();
        r[COL_ORIGINE] = ORIGINE_UTENTE;
        r[COL_CHIAVE_DEFAULT] = chiaveDefault == null ? "" : chiaveDefault;

        List<String> errori = Principale_PeriodiExchange.validaPeriodi(java.util.Collections.singletonList(r));
        if (!errori.isEmpty()) {
            Messaggi.WarningMessage("Dati non validi", String.join("\n", errori), this);
            return;
        }
        risultato = r;
        confermato = true;
        dispose();
    }//GEN-LAST:event_Bottone_OkActionPerformed

    private void Bottone_AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone_AnnullaActionPerformed
        dispose();
    }//GEN-LAST:event_Bottone_AnnullaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone_Annulla;
    private javax.swing.JButton Bottone_Ok;
    private javax.swing.JTextField Campo_Ident;
    private javax.swing.JTextField Campo_Nome;
    private javax.swing.JTextArea Campo_Fonte;
    private javax.swing.JTextArea Campo_Note;
    private javax.swing.JTextField Campo_Prog;
    private javax.swing.JComboBox Combo_Stato;
    private com.toedter.calendar.JDateChooser Data_Fine;
    private com.toedter.calendar.JDateChooser Data_Inizio;
    private javax.swing.JLabel Label_DataFine;
    private javax.swing.JLabel Label_DataInizio;
    private javax.swing.JLabel Label_Fonte;
    private javax.swing.JLabel Label_Ident;
    private javax.swing.JLabel Label_Nome;
    private javax.swing.JLabel Label_Note;
    private javax.swing.JLabel Label_Prog;
    private javax.swing.JLabel Label_Stato;
    private javax.swing.JPanel Pannello_Campi;
    private javax.swing.JPanel Pannello_Pulsanti;
    private javax.swing.JScrollPane Scroll_Fonte;
    private javax.swing.JScrollPane Scroll_Note;
    // End of variables declaration//GEN-END:variables
}
