Panel.background = #1e1e1e
RootPane.background = #1e1e1e
window = #1a1a1a
desktop = #181818

TextField.background = #242424
TextArea.background = #242424
PasswordField.background = #242424
FormattedTextField.background = #242424
EditorPane.background = #242424

ComboBox.background = #242424
Spinner.background = #242424
ScrollPane.background = #1e1e1e
Viewport.background = #1e1e1e

Table.background = #202020
Tree.background = #1e1e1e
List.background = #1e1e1e

TabbedPane.background = #1b1b1b
TabbedPane.selectedBackground = darken($TabbedPane.background,5%)

Button.background = #2a2a2a
Button.default.background = #3b82f6