name: Build multi-platform app-image

env:
  PROJECT_NAME: Giacenze_Crypto
  JAVA_VERSION: 21
  BUILD_DIR: build
  VERSIONE: 1.0.42

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM on Windows
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build JAR with Maven
        run: mvn clean package
        
      - name: Prepara cartella build con risorse
        run: |
            mkdir -p build/immagini
            cp -r immagini/* build/immagini/
            cp logo.png build/
            cp GestitiCoincap.csv build/
        
      - name: Build Windows app-image
        shell: pwsh
        run: |
          jpackage `
            --type app-image `
            --input build `
            --dest out/windows `
            --name $env:PROJECT_NAME `
            --main-jar Giacenze_Crypto.jar `
            --main-class com.giacenzecrypto.giacenze_crypto.Giacenze_Crypto `
            --icon logo.ico `
            --app-version $env:VERSIONE `
            --vendor Luca
          
      - name: Move resources to root (Windows)
        run: |
            Move-Item -Path "out/windows/$env:PROJECT_NAME/app/immagini" -Destination "out/windows/$env:PROJECT_NAME/immagini"
            Move-Item -Path "out/windows/$env:PROJECT_NAME/app/logo.png" -Destination "out/windows/$env:PROJECT_NAME/logo.png"
            Move-Item -Path "out/windows/$env:PROJECT_NAME/app/GestitiCoincap.csv" -Destination "out/windows/$env:PROJECT_NAME/GestitiCoincap.csv"
            
      - uses: actions/upload-artifact@v4
        with:
          name: windows-app-image
          path: out/windows/${{ env.PROJECT_NAME }}

