name: Build multi-platform app-image

env:
  PROJECT_NAME: Giacenze_Crypto
  JAVA_VERSION: 21
  BUILD_DIR: build
  VERSIONE: 1.0.42

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM on Windows
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
        
      - name: Copy extra resources (immagini/, logo.png, GestitiCoincap.csv)
        shell: cmd
        run: |
          mkdir target\extra\immagini
          xcopy immagini\* build\immagini\ /E /I /Y
          copy logo.png build\extra\
          copy GestitiCoincap.csv build\extra\
        
      - name: Build Windows app-image
        shell: pwsh
        run: |
          jpackage `
            --type app-image `
            --input build `
            --dest out/windows `
            --name $env:PROJECT_NAME `
            --main-jar Giacenze_Crypto.jar `
            --main-class com.giacenzecrypto.giacenze_crypto.Giacenze_Crypto `
            --icon logo.ico `
            --app-version $env:VERSIONE `
            --vendor Luca `
            --resource-dir target/extra
      - uses: actions/upload-artifact@v4
        with:
          name: windows-app-image
          path: out/windows/${{ env.PROJECT_NAME }}
