name: MacOS

env:
  PROJECT_NAME: Giacenze_Crypto
  JAVA_VERSION: 21
  BUILD_DIR: build

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM on macOS
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Setup Python virtualenv and install Pillow
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install pillow

      - name: Convert logo.png to .icns
        run: |
          source venv/bin/activate
          python3 Python/generate_icns.py
          iconutil -c icns icon.iconset -o logo.icns    

      - name: Estrai versione dal pom.xml
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSIONE=$VERSION" >> $GITHUB_ENV

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Prepare input directory for jpackage
        run: |
          mkdir -p build/Immagini
          cp -r Immagini/* build/Immagini/
          cp logo.png build/
          cp GestitiCoincap.csv build/
          cp target/Giacenze_Crypto-${VERSIONE}-jar-with-dependencies.jar build/Giacenze_Crypto.jar

      - name: Build macOS .dmg
        run: |
          WORKDIR="HOME/Library/Application Support/GiacenzeCrypto/"
          jpackage \
            --type dmg \
            --input build \
            --dest out/dmg \
            --name ${{ env.PROJECT_NAME }} \
            --main-jar Giacenze_Crypto.jar \
            --main-class com.giacenzecrypto.giacenze_crypto.Giacenze_Crypto \
            --arguments "--workdir \"$WORKDIR\"" \
            --icon logo.icns \
            --app-version ${{ env.VERSIONE }} \
            --vendor Luca

      - name: Debug macOS output
        run: |
          ls -R out/dmg

      - name: Upload .dmg
        uses: actions/upload-artifact@v4
        with:
          name: GiacenzeCrypto_${{ env.VERSIONE }}_Beta_DMG_MacOS
          path: out/dmg/*.dmg

