name: Windows
env:
  PROJECT_NAME: Giacenze_Crypto
  JAVA_VERSION: 21
  BUILD_DIR: build
on:
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM on Windows
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          
      - name: Estrai versione dal pom.xml
        shell: pwsh
        run: |
            [xml]$pom = Get-Content pom.xml
            $version = $pom.project.version
            if (-not $version) {
            Write-Error "Versione non trovata nel pom.xml"
            exit 1
            }
            Write-Host "Versione estratta: $version"
            echo "VERSIONE=$version" >> $env:GITHUB_ENV
          
      - name: Build JAR with Maven
        run: mvn clean package -DskipTests
        
      - name: Prepara cartella build con risorse
        shell: pwsh
        run: |
            mkdir -p build/immagini
            cp -r immagini/* build/immagini/
            mkdir -p build/Scripts
            cp -r Scripts/* build/Scripts/
            cp logo.png build/
            cp GestitiCoincap.csv build/
            cp target/Giacenze_Crypto-$env:VERSIONE-jar-with-dependencies.jar build/Giacenze_Crypto.jar
        
      - name: Build Windows app-image
        shell: pwsh
        run: |
          jpackage `
            --type app-image `
            --input build `
            --dest out/windows `
            --name $env:PROJECT_NAME `
            --main-jar Giacenze_Crypto.jar `
            --main-class com.giacenzecrypto.giacenze_crypto.Giacenze_Crypto `
            --arguments "--risorse app/" `
            --icon logo.ico `
            --app-version $env:VERSIONE `
            --vendor Luca

      - name: Build MSI installer package
        shell: pwsh
        run: |
          jpackage `
            --type msi `
            --input build `
            --dest out/msi `
            --name $env:PROJECT_NAME `
            --main-jar Giacenze_Crypto.jar `
            --main-class com.giacenzecrypto.giacenze_crypto.Giacenze_Crypto `
            --arguments "--risorse app/" `
            --icon logo.ico `
            --app-version $env:VERSIONE `
            --vendor Luca `
            --win-menu `
            --win-shortcut `
            --win-dir-chooser `
            --win-upgrade-uuid "123e4567-e89b-12d3-a456-426614174000"
            
      - uses: actions/upload-artifact@v4
        with:
          name: GiacenzeCrypto_${{ env.VERSIONE }}_Beta_Portable_Windows
          path: out/windows/${{ env.PROJECT_NAME }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: GiacenzeCrypto_${{ env.VERSIONE }}_Beta_MSI_Installer
          path: out/msi
